//! Integration test: blueprint-portrait.pdf → extract image → tile pyramid.
//!
//! blueprint-portrait.pdf is a scanned portrait-orientation blueprint with a
//! single embedded 3300x5024 Gray8 raster image. The tests verify that libviprs
//! produces output matching the vips-generated expected fixtures.
//!
//! Expected fixtures were generated by libvips (vips 8.14.1) with:
//!   vips dzsave extracted_blueprint_portrait.png blueprint_portrait_expected \
//!     --layout dz --tile-size 256 --overlap 0 --suffix .png --strip
//!
//! Comparison is done at the decoded-pixel level: both PNGs are decoded to raw
//! pixel data and compared, so differences in PNG encoding do not cause failures.
//!
//! Source: 3300x5024 Gray8, 14 levels, 367 tiles.

use std::path::{Path, PathBuf};

use libviprs::{
    EngineConfig, FsSink, Layout, MemorySink, PixelFormat, PyramidPlanner, TileFormat,
    extract_page_image, generate_pyramid,
};

const FIXTURE_PDF: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/blueprint-portrait.pdf"
);

const EXPECTED_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/blueprint_portrait_expected"
);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn collect_files(dir: &Path, ext: &str) -> Vec<(String, Vec<u8>)> {
    let mut files = Vec::new();
    collect_files_recursive(dir, dir, ext, &mut files);
    files.sort_by(|a, b| a.0.cmp(&b.0));
    files
}

fn collect_files_recursive(root: &Path, dir: &Path, ext: &str, out: &mut Vec<(String, Vec<u8>)>) {
    if !dir.is_dir() {
        return;
    }
    for entry in std::fs::read_dir(dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.is_dir() {
            collect_files_recursive(root, &path, ext, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some(ext) {
            let rel = path
                .strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .to_string();
            let bytes = std::fs::read(&path).unwrap();
            out.push((rel, bytes));
        }
    }
}

/// Decode a PNG file to raw pixels for comparison.
/// Returns (width, height, raw_pixels).
fn decode_png(data: &[u8]) -> (u32, u32, Vec<u8>) {
    let img = image::load_from_memory_with_format(data, image::ImageFormat::Png)
        .expect("failed to decode PNG");
    let w = img.width();
    let h = img.height();
    let raw = img.into_bytes();
    (w, h, raw)
}

/// Compare two sets of PNG tile files by decoding to pixels.
///
/// vips produces tiles at their natural (unpadded) size, while libviprs pads
/// edge tiles to `tile_size` with background (white). This function compares
/// the overlapping pixel region and verifies any padding is solid background.
///
/// A per-channel `tolerance` allows for minor differences in downscaling
/// algorithms (vips uses libvips area averaging, libviprs uses its own
/// implementation — rounding differences accumulate at lower pyramid levels).
fn assert_tiles_pixel_equal_tol(
    expected_files: &[(String, Vec<u8>)],
    actual_files: &[(String, Vec<u8>)],
    context: &str,
    tolerance: u8,
) {
    let mut global_max_diff: u8 = 0;
    let mut max_diff_path = String::new();
    assert_eq!(
        expected_files.len(),
        actual_files.len(),
        "{context}: tile count mismatch: expected {}, got {}",
        expected_files.len(),
        actual_files.len(),
    );

    for ((exp_path, exp_bytes), (act_path, act_bytes)) in
        expected_files.iter().zip(actual_files.iter())
    {
        assert_eq!(
            exp_path, act_path,
            "{context}: path mismatch: expected {exp_path}, got {act_path}"
        );
        let (ew, eh, epx) = decode_png(exp_bytes);
        let (aw, ah, apx) = decode_png(act_bytes);

        // Both tiles must cover at least the vips region
        assert!(
            aw >= ew && ah >= eh,
            "{context}: libviprs tile {act_path} ({aw}x{ah}) smaller than vips ({ew}x{eh})"
        );

        // Detect channel count from decoded data
        let exp_channels = epx.len() / (ew as usize * eh as usize);
        let act_channels = apx.len() / (aw as usize * ah as usize);
        assert_eq!(
            exp_channels, act_channels,
            "{context}: channel count mismatch at {act_path}: vips {exp_channels}, libviprs {act_channels}"
        );
        let ch = exp_channels;

        // Compare overlapping pixel region
        for y in 0..eh as usize {
            let exp_row_start = y * ew as usize * ch;
            let act_row_start = y * aw as usize * ch;
            for x in 0..(ew as usize * ch) {
                let ev = epx[exp_row_start + x];
                let av = apx[act_row_start + x];
                let diff = (ev as i16 - av as i16).unsigned_abs() as u8;
                if diff > global_max_diff {
                    global_max_diff = diff;
                    max_diff_path = act_path.clone();
                }
                assert!(
                    diff <= tolerance,
                    "{context}: pixel mismatch at {act_path} row={y} col={} \
                     vips={ev} libviprs={av} diff={diff} tolerance={tolerance}",
                    x / ch
                );
            }
        }

        // Verify padding is background (255 for all channels)
        if aw > ew {
            for y in 0..ah as usize {
                let pad_start = y * aw as usize * ch + ew as usize * ch;
                let pad_end = y * aw as usize * ch + aw as usize * ch;
                assert!(
                    apx[pad_start..pad_end].iter().all(|&b| b == 255),
                    "{context}: right padding not white at row {y} in {act_path}"
                );
            }
        }
        if ah > eh {
            for y in eh as usize..ah as usize {
                let row_start = y * aw as usize * ch;
                let row_end = row_start + aw as usize * ch;
                assert!(
                    apx[row_start..row_end].iter().all(|&b| b == 255),
                    "{context}: bottom padding not white at row {y} in {act_path}"
                );
            }
        }
    }

    eprintln!(
        "{context}: max pixel diff = {global_max_diff} (at {max_diff_path}), tolerance = {tolerance}"
    );
}

fn load_blueprint_portrait() -> libviprs::Raster {
    extract_page_image(Path::new(FIXTURE_PDF), 1)
        .expect("failed to extract image from blueprint-portrait.pdf")
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

/// Verify the extracted raster has the expected dimensions and pixel format.
#[test]
fn blueprint_portrait_extraction_metadata() {
    let raster = load_blueprint_portrait();

    assert_eq!(raster.width(), 3300);
    assert_eq!(raster.height(), 5024);
    assert_eq!(raster.format(), PixelFormat::Gray8);
}

/// Verify the CLI-generated fixtures are structurally valid: correct tile
/// count, all files are valid PNGs, and the DZI manifest matches.
#[test]
fn blueprint_portrait_cli_fixtures_valid() {
    let expected_files = collect_files(Path::new(EXPECTED_DIR), "png");
    assert_eq!(
        expected_files.len(),
        367,
        "Expected 367 tiles from CLI, got {}",
        expected_files.len(),
    );

    // Every tile should be a valid PNG
    for (path, bytes) in &expected_files {
        assert!(
            bytes.len() > 8,
            "Tile {path} is too small to be a PNG ({} bytes)",
            bytes.len(),
        );
        assert_eq!(
            &bytes[..4],
            &[0x89, b'P', b'N', b'G'],
            "Tile {path} does not have PNG magic bytes",
        );
    }

    // DZI manifest should exist and contain correct dimensions
    let dzi_path = PathBuf::from(EXPECTED_DIR).with_extension("dzi");
    let manifest = std::fs::read_to_string(&dzi_path).expect("DZI manifest not found");
    assert!(manifest.contains("Width=\"3300\""), "DZI missing width");
    assert!(manifest.contains("Height=\"5024\""), "DZI missing height");
    assert!(
        manifest.contains("TileSize=\"256\""),
        "DZI missing tile size"
    );
    assert!(manifest.contains("Format=\"png\""), "DZI missing format");
}

/// Generate a pyramid with libviprs and compare every tile's decoded pixels
/// against the vips-generated expected fixtures.
#[test]
fn blueprint_portrait_pyramid_matches_expected() {
    let raster = load_blueprint_portrait();

    let planner = PyramidPlanner::new(raster.width(), raster.height(), 256, 0, Layout::DeepZoom)
        .expect("failed to create pyramid planner");
    let plan = planner.plan();

    assert_eq!(plan.level_count(), 14);

    let dir = tempfile::tempdir().unwrap();
    let base = dir.path().join("blueprint_portrait");
    let sink = FsSink::new(base.clone(), plan.clone(), TileFormat::Png);
    let config = EngineConfig::default();

    let result =
        generate_pyramid(&raster, &plan, &sink, &config).expect("pyramid generation failed");

    assert_eq!(result.tiles_produced, plan.total_tile_count());

    // Compare tiles (decoded pixel comparison — PNG encoding may differ).
    // Tolerance of 1 allows for rounding differences in downscaling algorithms
    // between vips (libvips area averaging) and libviprs.
    let expected_files = collect_files(Path::new(EXPECTED_DIR), "png");
    let actual_files = collect_files(&base, "png");
    // Tolerance accounts for downscaling algorithm differences between vips
    // (libvips area averaging) and libviprs. Maximum observed diff is ~103 at
    // deep levels where rounding compounds. Full-resolution tiles (level 13)
    // should match exactly since no downscaling is involved.
    assert_tiles_pixel_equal_tol(&expected_files, &actual_files, "portrait DeepZoom", 0);

    // Compare DZI manifest (semantic check — vips and libviprs may format XML differently)
    let expected_dzi = std::fs::read_to_string(PathBuf::from(EXPECTED_DIR).with_extension("dzi"))
        .expect("expected DZI manifest not found");
    let actual_dzi = std::fs::read_to_string(dir.path().join("blueprint_portrait.dzi"))
        .expect("generated DZI manifest not found");

    // Check key attributes rather than exact string match
    for attr in [
        "Width=\"3300\"",
        "Height=\"5024\"",
        "TileSize=\"256\"",
        "Overlap=\"0\"",
        "Format=\"png\"",
    ] {
        assert!(actual_dzi.contains(attr), "DZI missing {attr}");
        assert!(expected_dzi.contains(attr), "Expected DZI missing {attr}");
    }
}

/// Concurrent generation matches the vips-generated fixtures.
#[test]
fn blueprint_portrait_pyramid_concurrent_matches_expected() {
    let raster = load_blueprint_portrait();

    let planner = PyramidPlanner::new(raster.width(), raster.height(), 256, 0, Layout::DeepZoom)
        .expect("failed to create pyramid planner");
    let plan = planner.plan();

    let dir = tempfile::tempdir().unwrap();
    let base = dir.path().join("blueprint_portrait");
    let sink = FsSink::new(base.clone(), plan.clone(), TileFormat::Png);
    let config = EngineConfig::default().with_concurrency(4);

    let result =
        generate_pyramid(&raster, &plan, &sink, &config).expect("pyramid generation failed");

    assert_eq!(result.tiles_produced, plan.total_tile_count());

    let expected_files = collect_files(Path::new(EXPECTED_DIR), "png");
    let actual_files = collect_files(&base, "png");
    assert_tiles_pixel_equal_tol(&expected_files, &actual_files, "portrait concurrent", 0);
}

/// Verify determinism: two runs produce identical output.
#[test]
fn blueprint_portrait_pyramid_deterministic() {
    let raster = load_blueprint_portrait();

    let planner = PyramidPlanner::new(raster.width(), raster.height(), 256, 0, Layout::DeepZoom)
        .expect("failed to create pyramid planner");
    let plan = planner.plan();

    let sink1 = MemorySink::new();
    let sink2 = MemorySink::new();
    let config = EngineConfig::default();

    generate_pyramid(&raster, &plan, &sink1, &config).unwrap();
    generate_pyramid(&raster, &plan, &sink2, &config).unwrap();

    let mut tiles1 = sink1.tiles();
    let mut tiles2 = sink2.tiles();
    tiles1.sort_by_key(|t| (t.coord.level, t.coord.row, t.coord.col));
    tiles2.sort_by_key(|t| (t.coord.level, t.coord.row, t.coord.col));

    assert_eq!(tiles1.len(), tiles2.len());
    for (t1, t2) in tiles1.iter().zip(tiles2.iter()) {
        assert_eq!(t1.coord, t2.coord);
        assert_eq!(t1.data, t2.data, "Tile {:?} differs between runs", t1.coord);
    }
}

// ---------------------------------------------------------------------------
// PDFium-rendered portrait pyramid vs vips fixture comparison
// ---------------------------------------------------------------------------

#[cfg(feature = "pdfium")]
const RENDERED_PORTRAIT_FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/rendered_blueprint_portrait.png"
);
#[cfg(feature = "pdfium")]
const RENDERED_PORTRAIT_EXPECTED: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/blueprint_portrait_rendered_expected"
);

#[cfg(feature = "pdfium")]
fn load_rendered_portrait() -> libviprs::Raster {
    libviprs::decode_file(Path::new(RENDERED_PORTRAIT_FIXTURE))
        .expect("failed to load rendered_blueprint_portrait.png")
}

/// Generate a pyramid from the pdfium-rendered portrait PNG and compare
/// every tile against the vips-generated fixtures.
#[test]
#[cfg(feature = "pdfium")]
fn blueprint_portrait_rendered_pyramid_matches_vips() {
    let raster = load_rendered_portrait();

    let planner = PyramidPlanner::new(raster.width(), raster.height(), 256, 0, Layout::DeepZoom)
        .expect("failed to create pyramid planner");
    let plan = planner.plan();

    let dir = tempfile::tempdir().unwrap();
    let base = dir.path().join("portrait_rendered");
    let sink = FsSink::new(base.clone(), plan.clone(), TileFormat::Png);

    let result = generate_pyramid(&raster, &plan, &sink, &EngineConfig::default()).unwrap();
    assert_eq!(result.tiles_produced, plan.total_tile_count());

    let expected_files = collect_files(Path::new(RENDERED_PORTRAIT_EXPECTED), "png");
    let actual_files = collect_files(&base, "png");
    // Tolerance of 5 for RGBA: minor rounding in alpha-channel averaging
    assert_tiles_pixel_equal_tol(
        &expected_files,
        &actual_files,
        "rendered portrait vs vips",
        5,
    );
}

/// Concurrent rendered portrait pyramid matches vips fixtures.
#[test]
#[cfg(feature = "pdfium")]
fn blueprint_portrait_rendered_pyramid_concurrent_matches_vips() {
    let raster = load_rendered_portrait();

    let planner = PyramidPlanner::new(raster.width(), raster.height(), 256, 0, Layout::DeepZoom)
        .expect("failed to create pyramid planner");
    let plan = planner.plan();

    let dir = tempfile::tempdir().unwrap();
    let base = dir.path().join("portrait_rendered");
    let sink = FsSink::new(base.clone(), plan.clone(), TileFormat::Png);
    let config = EngineConfig::default().with_concurrency(4);

    let result = generate_pyramid(&raster, &plan, &sink, &config).unwrap();
    assert_eq!(result.tiles_produced, plan.total_tile_count());

    let expected_files = collect_files(Path::new(RENDERED_PORTRAIT_EXPECTED), "png");
    let actual_files = collect_files(&base, "png");
    assert_tiles_pixel_equal_tol(
        &expected_files,
        &actual_files,
        "rendered portrait concurrent vs vips",
        5,
    );
}
