//! `OP_MAP.md`'s count summary has to be what its own tables say
//! (libviprs/libviprs-cli#67).
//!
//! `libviprs-cli/OP_MAP.md` is the CLI's source of truth for op coverage, and
//! its count summary (the headline numbers, the per-class table and the
//! per-family table, plus the audit trail and the foreign headline) used to be
//! regenerated by eye. By the time of the #67 refresh it disagreed with the
//! tables underneath it in four families. These tests recount every table row
//! and hold the summary to the recount, so a row added without touching the
//! summary, or a class changed in one place only, fails here.
//!
//! The second test holds the map to the binary: the set of commands the op
//! tables imply has to be the set of op-family commands `viprs __dump-commands`
//! reports, and the same for the foreign section, so a command that ships
//! without a row (or a row whose command never shipped) fails too.
//!
//! Both read the sibling `libviprs-cli` checkout and skip cleanly without it,
//! with the same `$VIPRS_REQUIRE_CLI` false-green guard as the differential
//! cells.

mod common;

use std::collections::{BTreeMap, BTreeSet};

use common::cli::{cli_available, cli_dir, run_viprs_ok};

/// The seven oracle classes, in the order the summary tables list them.
const CLASSES: [&str; 7] = [
    "EXACT",
    "EXACT-AFTER-CAST",
    "BOUNDED-TOL",
    "FOURIER",
    "GOLDEN-ONLY",
    "EXCLUDED",
    "DEFERRED",
];

fn skip_if_no_cli(test: &str) -> bool {
    if cli_available() && cli_dir().join("OP_MAP.md").is_file() {
        return false;
    }
    eprintln!(
        "SKIP {test}: libviprs-cli sibling (and its OP_MAP.md) not checked out \
         (set $VIPRS_CLI_DIR, or run in the cli-differential job)."
    );
    true
}

fn op_map() -> String {
    let path = cli_dir().join("OP_MAP.md");
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()))
}

/// The cells of a markdown table row, trimmed. `\|` inside a cell is an
/// escaped pipe, not a separator.
fn cells(line: &str) -> Vec<String> {
    let inner = line.trim().trim_start_matches('|').trim_end_matches('|');
    let mut out = Vec::new();
    let mut cur = String::new();
    let mut chars = inner.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '\\' && chars.peek() == Some(&'|') {
            cur.push('|');
            chars.next();
        } else if c == '|' {
            out.push(cur.trim().to_string());
            cur.clear();
        } else {
            cur.push(c);
        }
    }
    out.push(cur.trim().to_string());
    out
}

/// A number in bold, `**247**` -> 247, taken from the first bold run after
/// `label` on the same line.
fn bold_after(text: &str, label: &str) -> u64 {
    let at = text
        .find(label)
        .unwrap_or_else(|| panic!("OP_MAP.md has no {label:?}"));
    let rest = &text[at + label.len()..];
    let start = rest.find("**").expect("a bold number follows") + 2;
    let end = start + rest[start..].find("**").expect("bold closes");
    rest[start..end]
        .split_whitespace()
        .next()
        .unwrap()
        .parse()
        .unwrap_or_else(|_| panic!("{label:?} is not followed by a bold number"))
}

/// The first plain integer after `label` on the same line, with `**` ignored.
fn number_after(text: &str, label: &str) -> u64 {
    let at = text
        .find(label)
        .unwrap_or_else(|| panic!("OP_MAP.md has no {label:?}"));
    let line_end = text[at..].find('\n').map_or(text.len(), |n| at + n);
    let digits: String = text[at + label.len()..line_end]
        .chars()
        .skip_while(|c| !c.is_ascii_digit())
        .take_while(char::is_ascii_digit)
        .collect();
    digits
        .parse()
        .unwrap_or_else(|_| panic!("no number after {label:?}"))
}

/// One op row: family key, `vips_nickname` with any fold marker stripped, and
/// its oracle class.
struct OpRow {
    family: String,
    nickname: String,
    class: String,
}

/// Every row of every op-family table, i.e. everything between the column
/// legend and the foreign section whose first cell is a backticked fn name.
///
/// The family key is the first word of the `## ` heading the row sits under,
/// except that a row marked `*(resize.rs)*` belongs to `resize`, which the
/// summary counts on its own line although it shares resample's table.
fn op_rows(text: &str) -> Vec<OpRow> {
    let ops = text.split("\n## foreign").next().unwrap();
    let mut family: Option<String> = None;
    let mut rows = Vec::new();
    for line in ops.lines() {
        if let Some(h) = line.strip_prefix("## ") {
            family = if h.contains("(src/") {
                Some(h.split_whitespace().next().unwrap().to_string())
            } else {
                None
            };
            continue;
        }
        let Some(fam) = &family else { continue };
        if !line.starts_with("| `") {
            continue;
        }
        let c = cells(line);
        assert!(c.len() >= 5, "op row with fewer than five cells: {line}");
        let family = if c[0].contains("*(resize.rs)*") {
            "resize".to_string()
        } else {
            fam.clone()
        };
        let nickname = c[1]
            .replace("*(fold)*", "")
            .trim()
            .trim_matches('`')
            .to_string();
        let class = c[3].clone();
        assert!(
            CLASSES.contains(&class.as_str()),
            "row {line:?} has oracle class {class:?}, not one of {CLASSES:?}"
        );
        rows.push(OpRow {
            family,
            nickname,
            class,
        });
    }
    rows
}

/// The markdown table that starts on the first line beginning with `header`.
fn table_after(text: &str, header: &str) -> Vec<Vec<String>> {
    let at = text
        .find(header)
        .unwrap_or_else(|| panic!("OP_MAP.md has no table headed {header:?}"));
    text[at..]
        .lines()
        .take_while(|l| l.starts_with('|'))
        .skip(2)
        .map(cells)
        .collect()
}

/// The op-family command set the tables imply: one per distinct nickname over
/// the rows that are not EXCLUDED.
fn op_commands(rows: &[OpRow]) -> BTreeSet<String> {
    rows.iter()
        .filter(|r| r.class != "EXCLUDED")
        .map(|r| r.nickname.clone())
        .collect()
}

/// Foreign rows: (nickname, class) for the save and load tables, and the
/// EXCLUDED table's length.
fn foreign_rows(text: &str) -> (Vec<(String, String)>, usize) {
    let section = text
        .split("\n## foreign")
        .nth(1)
        .expect("OP_MAP.md has a foreign section");
    let section = section.split("\n## Audit trail").next().unwrap();
    let mut live = Vec::new();
    let mut excluded = 0;
    let mut sub = "";
    for line in section.lines() {
        if let Some(h) = line.strip_prefix("### ") {
            sub = h.trim();
            continue;
        }
        if !line.starts_with('|') || line.starts_with("|---") || line.starts_with("| libviprs_fn") {
            continue;
        }
        let c = cells(line);
        match sub {
            "Save" | "Load" => {
                let class = c[2].split_whitespace().next().unwrap().to_string();
                live.push((c[1].trim_matches('`').to_string(), class));
            }
            "EXCLUDED" => excluded += 1,
            _ => {}
        }
    }
    (live, excluded)
}

#[test]
fn op_map_count_summary_matches_its_tables() {
    if skip_if_no_cli("op_map_count_summary") {
        return;
    }
    let text = op_map();
    let rows = op_rows(&text);
    assert!(rows.len() > 200, "parsed only {} op rows", rows.len());

    // Recount per family and per class.
    let mut by_family: BTreeMap<String, BTreeMap<String, u64>> = BTreeMap::new();
    let mut by_class: BTreeMap<String, u64> = BTreeMap::new();
    for r in &rows {
        *by_family
            .entry(r.family.clone())
            .or_default()
            .entry(r.class.clone())
            .or_default() += 1;
        *by_class.entry(r.class.clone()).or_default() += 1;
    }
    let total = rows.len() as u64;
    let class = |c: &str| by_class.get(c).copied().unwrap_or(0);

    let mut wrong = Vec::new();

    // The per-class table.
    for r in table_after(&text, "| oracle_class | rows |") {
        let want: u64 = r[1].trim_matches('*').parse().unwrap();
        if class(&r[0]) != want {
            wrong.push(format!(
                "class {}: summary {want}, tables {}",
                r[0],
                class(&r[0])
            ));
        }
    }

    // The per-family table: rows, then EXACT EAC BT FOURIER GOLDEN EXCLUDED.
    let mut seen = BTreeSet::new();
    for r in table_after(&text, "| family | rows |") {
        let label = r[0].trim_matches('*');
        if label == "total" {
            let want: u64 = r[1].trim_matches('*').parse().unwrap();
            if want != total {
                wrong.push(format!("family total: summary {want}, tables {total}"));
            }
            continue;
        }
        let fam = label.split_whitespace().next().unwrap().to_string();
        seen.insert(fam.clone());
        let got = by_family.get(&fam).cloned().unwrap_or_default();
        let got_rows: u64 = got.values().sum();
        let want_rows: u64 = r[1].parse().unwrap();
        if got_rows != want_rows {
            wrong.push(format!(
                "{fam} rows: summary {want_rows}, tables {got_rows}"
            ));
        }
        for (i, c) in CLASSES[..6].iter().enumerate() {
            let want: u64 = r[2 + i].parse().unwrap();
            let have = got.get(*c).copied().unwrap_or(0);
            if have != want {
                wrong.push(format!("{fam} {c}: summary {want}, tables {have}"));
            }
        }
    }
    for fam in by_family.keys() {
        if !seen.contains(fam) {
            wrong.push(format!("family {fam} has rows but no line in the summary"));
        }
    }

    // The headline.
    let oracle =
        class("EXACT") + class("EXACT-AFTER-CAST") + class("BOUNDED-TOL") + class("FOURIER");
    if bold_after(&text, "Rows (op base names):") != total {
        wrong.push(format!(
            "headline rows: {}, tables {total}",
            bold_after(&text, "Rows (op base names):")
        ));
    }
    let line = text
        .lines()
        .find(|l| l.starts_with("Rows (op base names):"))
        .unwrap();
    let next = text
        .lines()
        .skip_while(|l| !l.starts_with("Rows (op base names):"))
        .nth(1)
        .unwrap();
    let para = format!("{line} {next}");
    for (label, want) in [
        ("with a real vips differential oracle", oracle),
        ("GOLDEN-ONLY", class("GOLDEN-ONLY")),
        ("EXCLUDED", class("EXCLUDED")),
        ("DEFERRED", class("DEFERRED")),
    ] {
        // The number sits just before its label: "205 with a real ...".
        let at = para
            .find(label)
            .unwrap_or_else(|| panic!("headline has no {label:?}"));
        let before: String = para[..at]
            .trim_end()
            .trim_end_matches("**")
            .chars()
            .rev()
            .take_while(char::is_ascii_digit)
            .collect::<String>()
            .chars()
            .rev()
            .collect();
        let have: u64 = before.parse().unwrap_or(u64::MAX);
        if have != want {
            wrong.push(format!("headline {label:?}: {have}, tables {want}"));
        }
    }

    // Distinct commands, and how many of them are golden-only pins.
    let cmds = op_commands(&rows);
    let golden: BTreeSet<&String> = cmds
        .iter()
        .filter(|n| {
            rows.iter()
                .filter(|r| &r.nickname == *n && r.class != "EXCLUDED")
                .all(|r| r.class == "GOLDEN-ONLY")
        })
        .collect();
    let want_cmds = bold_after(&text, "command):");
    if want_cmds != cmds.len() as u64 {
        wrong.push(format!(
            "headline commands: {want_cmds}, tables {}",
            cmds.len()
        ));
    }
    let want_diff = bold_after(&text, "Of those,");
    let want_golden = bold_after(&text, "are differential-backed and");
    if want_diff != (cmds.len() - golden.len()) as u64 || want_golden != golden.len() as u64 {
        wrong.push(format!(
            "headline split: {want_diff} differential + {want_golden} golden, tables {} + {} \
             (golden: {golden:?})",
            cmds.len() - golden.len(),
            golden.len()
        ));
    }

    // The audit trail: per-module rows sum to the row total, pub fns to theirs.
    let trail = table_after(&text, "| module | pub fns |");
    let mut fns = 0;
    let mut base = 0;
    let mut trail_total = None;
    for r in &trail {
        if r[0].contains("total") {
            trail_total = Some((
                r[1].trim_matches('*').parse::<u64>().unwrap(),
                r[4].trim_matches('*').parse::<u64>().unwrap(),
            ));
        } else {
            fns += r[1].parse::<u64>().unwrap();
            base += r[4].parse::<u64>().unwrap();
        }
    }
    let (t_fns, t_base) = trail_total.expect("the audit trail has a total row");
    if t_fns != fns {
        wrong.push(format!(
            "audit trail pub fns: total {t_fns}, modules sum to {fns}"
        ));
    }
    if t_base != base || base != total {
        wrong.push(format!(
            "audit trail base rows: total {t_base}, modules sum to {base}, tables {total}"
        ));
    }

    // The foreign headline: "**47 rows: 32 commands (27 EXACT, 5 BOUNDED-TOL) and 15 EXCLUDED.**"
    let (live, excluded) = foreign_rows(&text);
    let f_exact = live.iter().filter(|(_, c)| c == "EXACT").count() as u64;
    let f_bt = live.iter().filter(|(_, c)| c == "BOUNDED-TOL").count() as u64;
    let f_cmds: BTreeSet<&String> = live.iter().map(|(n, _)| n).collect();
    let f_line = text
        .lines()
        .find(|l| l.starts_with("**") && l.contains(" rows: ") && l.contains("commands"))
        .expect("the foreign section has its headline");
    for (label, want) in [
        ("**", live.len() as u64 + excluded as u64),
        ("rows:", f_cmds.len() as u64),
        ("commands (", f_exact),
        ("EXACT,", f_bt),
        (" and ", excluded as u64),
    ] {
        let have = number_after(f_line, label);
        if have != want {
            wrong.push(format!(
                "foreign headline after {label:?}: {have}, tables {want}"
            ));
        }
    }

    assert!(
        wrong.is_empty(),
        "OP_MAP.md's count summary disagrees with its tables:\n  {}",
        wrong.join("\n  ")
    );
}

#[test]
fn op_map_commands_are_the_commands_viprs_ships() {
    if skip_if_no_cli("op_map_commands") {
        return;
    }
    let text = op_map();
    let mapped = op_commands(&op_rows(&text));
    let (live, _) = foreign_rows(&text);
    let mapped_foreign: BTreeSet<String> = live.into_iter().map(|(n, _)| n).collect();

    let dump: serde_json::Value =
        serde_json::from_str(&run_viprs_ok(&["__dump-commands", "--json"])).expect("dump is JSON");
    let mut shipped = BTreeSet::new();
    let mut shipped_foreign = BTreeSet::new();
    for c in dump["commands"].as_array().expect("commands array") {
        let name = c["name"].as_str().unwrap().to_string();
        match c["family"].as_str().unwrap_or("builtin") {
            "builtin" => {}
            "foreign" => {
                shipped_foreign.insert(name);
            }
            _ => {
                shipped.insert(name);
            }
        }
    }

    let unmapped: Vec<_> = shipped.difference(&mapped).collect();
    let unshipped: Vec<_> = mapped.difference(&shipped).collect();
    let f_unmapped: Vec<_> = shipped_foreign.difference(&mapped_foreign).collect();
    let f_unshipped: Vec<_> = mapped_foreign.difference(&shipped_foreign).collect();
    assert!(
        unmapped.is_empty()
            && unshipped.is_empty()
            && f_unmapped.is_empty()
            && f_unshipped.is_empty(),
        "OP_MAP.md and viprs disagree.\n  op commands viprs ships with no OP_MAP row: {unmapped:?}\n  \
         op commands OP_MAP maps that viprs does not ship: {unshipped:?}\n  \
         foreign commands with no row: {f_unmapped:?}\n  foreign rows with no command: {f_unshipped:?}"
    );
}
