//! CLI-DIFFERENTIAL suite — histogram family (a per-family Wave-2 lane,
//! CLI_CONTRACT.md §7, OP_MAP.md histogram section).
//!
//! Each test runs `viprs <op> …` on the COMMON committed inputs under
//! `tests/fixtures/cli/histogram/` and decode-compares its output against the
//! COMMITTED vips 8.18.4 reference at the op's §5 tolerance. The suite NEVER
//! runs vips: references are generated offline by `tools/gen_cli_expected.sh`
//! and committed. This cell copies the bands reference cell
//! (`cli_bands_diff.rs`) exactly — including the skip-guard /
//! `VIPRS_REQUIRE_CLI` discipline.
//!
//! # Oracle classes (measured, honest — OP_MAP.md + this wave's investigation)
//!
//! * **EXACT** (decode-compare tol 0): `hist_find` (+ `--band 0`, full range),
//!   `hist_find_indexed`, `hist_find_ndim`, `hist_cum`, `maplut`, and the
//!   boolean `hist_ismonotonic`. The count-producing ops write a **ushort**
//!   histogram where vips writes **uint**, so the generator casts the vips
//!   reference to ushort (a lossless narrowing while no count saturates); the
//!   two then agree bit-for-bit. `hist_find` matches only where the data reaches
//!   255 — vips trims trailing-zero bins to width max+1, the core keeps the full
//!   256 (a representational trim, not a count divergence). Count/LUT/histogram
//!   outputs are carried as the native `.v` container (vips tags them
//!   `histogram`, which pngsave has no colour route for — the `identity`
//!   situation); `hist_equal`/`maplut` write a plain b-w image → PNG.
//! * **BOUNDED-TOL**: `hist_norm` (≤1 LSB cumulative-norm rounding, measured
//!   max-abs-diff 1), `hist_equal` (≤1 LSB equalisation-LUT rounding, measured
//!   max-abs-diff 1), and the floating `hist_entropy` scalar (relative eps 1e-6).
//! * **GOLDEN-ONLY** (NO vips cross-oracle — the core genuinely diverges from
//!   vips; see the open questions in the wave report): `hist_match`,
//!   `hist_plot`, `hist_local`, and `percent`. Each reference is generated by
//!   `viprs` itself (deterministic) and the test is a **regression pin** locking
//!   the current core behaviour, NOT a parity claim. The divergences are real
//!   and MEASURED (not hidden by input choice):
//!   - `hist_match`: vips emits a `uint` LUT, the core a `uchar` index LUT; the
//!     mappings differ wholesale (measured max-abs-diff 254).
//!   - `hist_plot`: the core plots `max+1` rows, vips `max` rows (a systematic
//!     off-by-one in the graph height → dimensions never match).
//!   - `hist_local`: the core's sliding-window / border algorithm matches vips
//!     only for a 3×3 window; larger windows diverge (measured max-abs-diff 51
//!     at 5×5) and the CLAHE `--max-slope` path diverges further (60). We do NOT
//!     cherry-pick the coincidental 3×3 match (that would hide the divergence).
//!   - `percent`: the core returns "the smallest value whose cumulative count
//!     reaches P%" (at-or-below); vips returns "the threshold above which P% of
//!     pixels lie". The definitions differ (measured core = vips − 2 on a dense
//!     ramp), so there is no clean cross-oracle.
//!
//! If the `libviprs-cli` sibling is not checked out (the default CI `test` job
//! and the Docker gate clone only the core counterpart), every test SKIPS with
//! a clear message rather than failing — the dedicated `cli-differential` CI job
//! lays the CLI down and actually exercises these (CLI_CONTRACT.md §7).

mod common;

use std::path::PathBuf;
use std::sync::OnceLock;

use common::cli::{
    SCALAR_INT_EXACT, SCALAR_S3_REL_EPS, cli_available, cli_fixture, compare_scalar,
    decode_compare, read_scalar_fixture, run_viprs_ok,
};

use tempfile::TempDir;

/// EXACT oracle class: bit-exact decode comparison (CLI_CONTRACT.md §5).
const EXACT: f64 = 0.0;

/// BOUNDED-TOL for `hist_equal` (CLI_CONTRACT.md §5): ≤1 LSB. The equalisation
/// LUT rounds independently in the core and in vips; the two agree to within one
/// least-significant bit (measured max-abs-diff 1).
const HIST_EQUAL_TOL: f64 = 1.0;

/// Skip-guard: `true` (with a printed reason) when the CLI sibling is absent.
///
/// When `$VIPRS_REQUIRE_CLI=1` (the dedicated `cli-differential` CI job) an
/// absent sibling instead PANICS inside [`cli_available`], so this never returns
/// `true` there — a would-be silent skip becomes a hard failure.
fn skip_if_no_cli(test: &str) -> bool {
    if cli_available() {
        return false;
    }
    eprintln!(
        "SKIP {test}: libviprs-cli sibling not checked out \
         (set $VIPRS_CLI_DIR / $VIPRS_BIN, or run in the cli-differential job)."
    );
    true
}

/// Absolute path to a fresh output file inside a **process-lifetime** temp dir
/// (one [`TempDir`] reused for every case, reclaimed at process exit).
fn out_path(name: &str) -> PathBuf {
    static DIR: OnceLock<TempDir> = OnceLock::new();
    let dir = DIR.get_or_init(|| tempfile::tempdir().expect("create temp dir"));
    dir.path().join(name)
}

// Common committed inputs (tests/fixtures/cli/histogram/).
const GRAY: &str = "histogram/gray.png";
const RGB: &str = "histogram/rgb.png";
const INDEX: &str = "histogram/index.png";
// Committed histogram-shaped inputs (consumed by the histogram-consuming ops).
const HIST: &str = "histogram/hist.v";
const HISTCUM: &str = "histogram/histcum.v";
const HIST2: &str = "histogram/hist2.v";
const LUT: &str = "histogram/lut.v";

/// Convenience: the absolute string path of a committed fixture.
fn fx(rel: &str) -> String {
    cli_fixture(rel).to_str().unwrap().to_string()
}

/// Normalise vips's / viprs's boolean print form (`TRUE`/`FALSE`, or a `1`/`0`)
/// to a Rust `bool`, so the monotonicity scalar can be compared as the boolean
/// it is rather than parsed as a float (`TRUE` is not an `f64`).
fn parse_bool(s: &str) -> bool {
    let t = s.trim();
    match t.to_ascii_uppercase().as_str() {
        "TRUE" | "1" => true,
        "FALSE" | "0" => false,
        other => panic!("not a boolean scalar: {other:?}"),
    }
}

// ---------------------------------------------------------------------------
// hist_find — S1, per-band value histogram (EXACT via ushort cast). Carried as
// `.v` (vips tags the output `histogram`, which pngsave cannot colour-route).
// ---------------------------------------------------------------------------

#[test]
fn hist_find_matches_vips_exact() {
    if skip_if_no_cli("hist_find") {
        return;
    }
    let out = out_path("hist_find.v");
    run_viprs_ok(&["hist_find", &fx(GRAY), out.to_str().unwrap()]);
    decode_compare(&out, &cli_fixture("histogram/hist_find_expected.v"), EXACT);
}

// hist_find --band 0 on the 3-band rgb input -> a 1-band histogram. Exercises
// the `hist_find --band` fold (core `try_hist_find_band`). Band 0 is the full
// 0..255 gray ramp: vips TRIMS trailing-zero bins (width = max+1) while the core
// keeps the full 256, so they match bit-for-bit only where the data reaches 255
// (a band with max < 255 would mismatch on width alone — a representational
// trim, not a count divergence; see the wave report open question). The count
// comparison over the populated range is a genuine EXACT.
#[test]
fn hist_find_band_matches_vips_exact() {
    if skip_if_no_cli("hist_find_band") {
        return;
    }
    let out = out_path("hist_find_band.v");
    run_viprs_ok(&["hist_find", &fx(RGB), out.to_str().unwrap(), "--band", "0"]);
    decode_compare(
        &out,
        &cli_fixture("histogram/hist_find_band_expected.v"),
        EXACT,
    );
}

// hist_find --band 2 on the 3-band rgb input. Band 2 is a DIAGONAL gradient
// whose value histogram is triangular (31 nonzero bins, counts 1..16..1) —
// provably DISTINCT from band 0's uniform ramp histogram (16 bins, each count
// 16), so this case actually verifies that `--band N` reads band N: a bug that
// ignored N and always read band 0 would produce band 0's histogram and fail
// here. Band 2 reaches 255 (like band 0), so vips does not trailing-zero-trim
// and the count comparison over the full 256-bin range is a genuine EXACT.
#[test]
fn hist_find_band2_matches_vips_exact() {
    if skip_if_no_cli("hist_find_band2") {
        return;
    }
    let out = out_path("hist_find_band2.v");
    run_viprs_ok(&["hist_find", &fx(RGB), out.to_str().unwrap(), "--band", "2"]);
    decode_compare(
        &out,
        &cli_fixture("histogram/hist_find_band2_expected.v"),
        EXACT,
    );
}

// ---------------------------------------------------------------------------
// hist_find_indexed — S2 (2 fixed inputs), per-index sample sums (EXACT).
// ---------------------------------------------------------------------------

#[test]
fn hist_find_indexed_matches_vips_exact() {
    if skip_if_no_cli("hist_find_indexed") {
        return;
    }
    let out = out_path("hist_find_indexed.v");
    run_viprs_ok(&[
        "hist_find_indexed",
        &fx(GRAY),
        &fx(INDEX),
        out.to_str().unwrap(),
    ]);
    decode_compare(
        &out,
        &cli_fixture("histogram/hist_find_indexed_expected.v"),
        EXACT,
    );
}

// ---------------------------------------------------------------------------
// hist_find_ndim — S1 --bins, a 3-D histogram cube (EXACT). rgb --bins 4 gives
// a 4x4x4 (4-band) ushort output, exercising the cube path.
// ---------------------------------------------------------------------------

#[test]
fn hist_find_ndim_matches_vips_exact() {
    if skip_if_no_cli("hist_find_ndim") {
        return;
    }
    let out = out_path("hist_find_ndim.v");
    run_viprs_ok(&[
        "hist_find_ndim",
        &fx(RGB),
        out.to_str().unwrap(),
        "--bins",
        "4",
    ]);
    decode_compare(
        &out,
        &cli_fixture("histogram/hist_find_ndim_expected.v"),
        EXACT,
    );
}

// ---------------------------------------------------------------------------
// hist_cum — S1, cumulative histogram (EXACT).
// ---------------------------------------------------------------------------

#[test]
fn hist_cum_matches_vips_exact() {
    if skip_if_no_cli("hist_cum") {
        return;
    }
    let out = out_path("hist_cum.v");
    run_viprs_ok(&["hist_cum", &fx(HIST), out.to_str().unwrap()]);
    decode_compare(&out, &cli_fixture("histogram/hist_cum_expected.v"), EXACT);
}

// ---------------------------------------------------------------------------
// hist_norm — S1, normalise a histogram (BOUNDED-TOL ≤1 LSB). Normalising the
// CUMULATIVE histogram rounds `(v * (n-1) / max)` ±1 apart from vips on some
// entries (measured max-abs-diff 1). We normalise the cumulative (the realistic
// LUT-building input) rather than the raw histogram (which happens to give 0) —
// we do NOT switch inputs to fake EXACT (bands bandmean lesson).
// ---------------------------------------------------------------------------

/// BOUNDED-TOL for `hist_norm` (CLI_CONTRACT.md §5): ≤1 LSB cumulative-norm
/// rounding, measured max-abs-diff 1.
const HIST_NORM_TOL: f64 = 1.0;

#[test]
fn hist_norm_matches_vips_bounded_tol() {
    if skip_if_no_cli("hist_norm") {
        return;
    }
    let out = out_path("hist_norm.v");
    run_viprs_ok(&["hist_norm", &fx(HISTCUM), out.to_str().unwrap()]);
    decode_compare(
        &out,
        &cli_fixture("histogram/hist_norm_expected.v"),
        HIST_NORM_TOL,
    );
}

// ---------------------------------------------------------------------------
// hist_equal — S1, global equalisation (BOUNDED-TOL ≤1 LSB). Output is a plain
// b-w image → PNG.
// ---------------------------------------------------------------------------

#[test]
fn hist_equal_matches_vips_bounded_tol() {
    if skip_if_no_cli("hist_equal") {
        return;
    }
    let out = out_path("hist_equal.png");
    run_viprs_ok(&["hist_equal", &fx(GRAY), out.to_str().unwrap()]);
    decode_compare(
        &out,
        &cli_fixture("histogram/hist_equal_expected.png"),
        HIST_EQUAL_TOL,
    );
}

// ---------------------------------------------------------------------------
// maplut — S2 (LUT is the 2nd input, after OUT in vips order); map an image
// through a look-up table (EXACT). The LUT is a non-identity equalisation LUT
// (norm ∘ cum ∘ find) so the case is NON-vacuous — an identity LUT would be.
// ---------------------------------------------------------------------------

#[test]
fn maplut_matches_vips_exact() {
    if skip_if_no_cli("maplut") {
        return;
    }
    let out = out_path("maplut.png");
    run_viprs_ok(&["maplut", &fx(GRAY), out.to_str().unwrap(), &fx(LUT)]);
    decode_compare(&out, &cli_fixture("histogram/maplut_expected.png"), EXACT);
}

// ---------------------------------------------------------------------------
// hist_entropy — S3 scalar (BOUNDED-TOL, relative eps 1e-6). A UNIFORM 16-bin
// histogram (entropy = log2 16 = 4) AND a non-uniform cumulative histogram
// (entropy 7.76335) — the latter is the discriminating, non-round case a broken
// entropy could not accidentally reproduce.
// ---------------------------------------------------------------------------

#[test]
fn hist_entropy_matches_vips_bounded_tol() {
    if skip_if_no_cli("hist_entropy") {
        return;
    }
    let stdout = run_viprs_ok(&["hist_entropy", &fx(HIST)]);
    let expected = read_scalar_fixture("histogram/hist_entropy_expected.txt");
    compare_scalar(&stdout, expected, SCALAR_S3_REL_EPS);
}

#[test]
fn hist_entropy_nonuniform_matches_vips_bounded_tol() {
    if skip_if_no_cli("hist_entropy_nonuniform") {
        return;
    }
    let stdout = run_viprs_ok(&["hist_entropy", &fx(HISTCUM)]);
    let expected = read_scalar_fixture("histogram/hist_entropy_cum_expected.txt");
    compare_scalar(&stdout, expected, SCALAR_S3_REL_EPS);
}

// ---------------------------------------------------------------------------
// hist_ismonotonic — S3 boolean (EXACT). A raw histogram is NOT monotonic
// (FALSE); its cumulative IS (TRUE). Both arms discriminate — a broken op that
// always returned one value would fail one of them.
// ---------------------------------------------------------------------------

#[test]
fn hist_ismonotonic_false_matches_vips_exact() {
    if skip_if_no_cli("hist_ismonotonic_false") {
        return;
    }
    let stdout = run_viprs_ok(&["hist_ismonotonic", &fx(HIST)]);
    let expected = read_string_fixture("histogram/hist_ismonotonic_false_expected.txt");
    assert!(
        !parse_bool(&expected),
        "the raw histogram fixture must be FALSE"
    );
    assert_eq!(
        parse_bool(&stdout),
        parse_bool(&expected),
        "hist_ismonotonic(raw histogram) mismatch: got {stdout:?}, expected {expected:?}",
    );
}

#[test]
fn hist_ismonotonic_true_matches_vips_exact() {
    if skip_if_no_cli("hist_ismonotonic_true") {
        return;
    }
    let stdout = run_viprs_ok(&["hist_ismonotonic", &fx(HISTCUM)]);
    let expected = read_string_fixture("histogram/hist_ismonotonic_true_expected.txt");
    assert!(parse_bool(&expected), "the cumulative fixture must be TRUE");
    assert_eq!(
        parse_bool(&stdout),
        parse_bool(&expected),
        "hist_ismonotonic(cumulative) mismatch: got {stdout:?}, expected {expected:?}",
    );
}

// ---------------------------------------------------------------------------
// GOLDEN-ONLY regression pins (NO vips cross-oracle — the core diverges from
// vips; see the module header). Each reference is generated by `viprs` itself;
// the test locks the current core behaviour at tol 0 and MUST NOT be read as a
// vips-parity claim.
// ---------------------------------------------------------------------------

#[test]
fn hist_match_golden_pin() {
    if skip_if_no_cli("hist_match") {
        return;
    }
    let out = out_path("hist_match.v");
    run_viprs_ok(&["hist_match", &fx(HIST), &fx(HIST2), out.to_str().unwrap()]);
    // GOLDEN-ONLY: pinned against the viprs-generated reference, NOT vips (vips
    // emits a uint LUT with a wholesale-different mapping, measured diff 254).
    decode_compare(&out, &cli_fixture("histogram/hist_match_golden.v"), EXACT);
}

#[test]
fn hist_plot_golden_pin() {
    if skip_if_no_cli("hist_plot") {
        return;
    }
    let out = out_path("hist_plot.v");
    run_viprs_ok(&["hist_plot", &fx(HIST), out.to_str().unwrap()]);
    // GOLDEN-ONLY: the core plots max+1 rows, vips max rows — dimensions never
    // match, so there is no cross-oracle.
    decode_compare(&out, &cli_fixture("histogram/hist_plot_golden.v"), EXACT);
}

#[test]
fn hist_local_golden_pin() {
    if skip_if_no_cli("hist_local") {
        return;
    }
    let out = out_path("hist_local.png");
    // A 5×5 window: the core's sliding-window/border algorithm diverges from
    // vips here (measured diff 51), so this is a viprs regression pin.
    run_viprs_ok(&["hist_local", &fx(GRAY), out.to_str().unwrap(), "5", "5"]);
    decode_compare(&out, &cli_fixture("histogram/hist_local_golden.png"), EXACT);
}

#[test]
fn hist_local_clahe_golden_pin() {
    if skip_if_no_cli("hist_local_clahe") {
        return;
    }
    let out = out_path("hist_local_clahe.png");
    // The CLAHE `--max-slope` path diverges from vips even more (measured diff
    // 60); pinned to viprs. Exercises the `--max-slope` flag.
    run_viprs_ok(&[
        "hist_local",
        &fx(GRAY),
        out.to_str().unwrap(),
        "5",
        "5",
        "--max-slope",
        "3",
    ]);
    decode_compare(
        &out,
        &cli_fixture("histogram/hist_local_clahe_golden.png"),
        EXACT,
    );
}

#[test]
fn percent_golden_pin() {
    if skip_if_no_cli("percent") {
        return;
    }
    let stdout = run_viprs_ok(&["percent", &fx(GRAY), "50"]);
    // GOLDEN-ONLY: the core's percentile definition (smallest value whose
    // cumulative reaches P%) differs from vips's ("threshold above which P%
    // lie"); pinned to the viprs-generated value (integer-exact).
    let expected = read_scalar_fixture("histogram/percent_golden.txt");
    compare_scalar(&stdout, expected, SCALAR_INT_EXACT);
}

// ---------------------------------------------------------------------------
// Error path: a float `.v` input must be a typed exit-1 error, NOT a panic
// (the core histogram ops' read_flat aborts on a float raster — the CLI guards
// it, bands B2 / CLI_CONTRACT.md §8).
// ---------------------------------------------------------------------------

#[test]
fn hist_find_rejects_float_input_without_panicking() {
    if skip_if_no_cli("hist_find_float_reject") {
        return;
    }
    // hist_norm_expected.v is a uchar histogram; build a float input instead by
    // casting gray to float via viprs itself, then feed it to hist_find.
    let float_in = out_path("float_in.v");
    run_viprs_ok(&["cast", &fx(GRAY), float_in.to_str().unwrap(), "float"]);
    let out = out_path("float_out.v");
    let output = common::cli::run_viprs(&[
        "hist_find",
        float_in.to_str().unwrap(),
        out.to_str().unwrap(),
    ]);
    assert!(
        !output.status.success(),
        "hist_find on a float raster must exit non-zero, not succeed"
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("integer image"),
        "expected a typed 'integer image' error, got stderr: {stderr}"
    );
}

/// Read a committed text fixture verbatim (trimmed by the caller). Used for the
/// boolean `hist_ismonotonic` references, which are not float-parseable.
fn read_string_fixture(rel: &str) -> String {
    let path = cli_fixture(rel);
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read fixture {}: {e}", path.display()))
}
