//! Fail when the core grows a capability the CLI does not account for
//! (libviprs-tests#233).
//!
//! # The hole this closes
//!
//! `libviprs-cli` drifted behind the library for two months and nothing
//! noticed. `OP_MAP.md` was audited once against core `4629599`, and every
//! feature the core gained after that landed with no `viprs` surface and no
//! test that could go red for it. Closing that gap once does nothing about the
//! next one, so this guard reads the core's surface out of the core itself and
//! asks the CLI to account for every piece of it.
//!
//! # What "account for" means
//!
//! Three things, each read from the source rather than from a hand list,
//! because a hand list is exactly what drifted:
//!
//! 1. **Capability features.** Every feature in the core's `[features]` table
//!    is forwarded by a `libviprs-cli` feature (`x = ["libviprs/x"]`) that
//!    `viprs features` lists, or has a row in [`CORE_FEATURES_NOT_IN_CLI`]
//!    saying why the CLI has no use for it. The libviprs-tests half of the same
//!    question lives in `tests/ci_feature_coverage.rs`, next to the guard that
//!    already reads this crate's `[features]` table.
//! 2. **Public modules.** Every `pub mod` in the core's `lib.rs` has a row in
//!    [`MODULES`] saying how the CLI reaches it: an op family held to its
//!    `OP_MAP.md` section, the codec surface held to `OP_MAP.md`'s foreign
//!    section, a built-in `viprs` command (checked to exist in the CLI's
//!    `enum Command`), or not at all, with the reason. A new module with no
//!    row is red.
//! 3. **Op-shaped functions.** In an op-family module every `pub fn` has to be
//!    named in that family's `OP_MAP.md` section (a row, a fold note or the
//!    section's "non-op public API" paragraph), and in a codec module every
//!    load/save entry point has to be named in the foreign section, or sit in
//!    [`FN_EXCLUSIONS`] with a one-line reason.
//!
//! Every exclusion row is checked as hard as the surface is. A row for a
//! feature, module or function the core no longer has is red, and so is a row
//! for something the CLI turns out to cover after all, so renaming an excluded
//! item without touching the list fails here instead of leaving a row that
//! excuses nothing.
//!
//! # Where the facts come from
//!
//! All offline. The core is the `../libviprs` path dependency this crate
//! compiles against, which CI checks out at `COUNTERPART_REV`. The CLI is the
//! `../libviprs-cli` sibling (`$VIPRS_CLI_DIR` wins), which CI checks out at
//! `CLI_COUNTERPART_REV`: its `Cargo.toml`, the `FEATURES` table in
//! `src/features.rs` (exactly what `viprs features --json` prints), the
//! `enum Command` in `src/main.rs`, and `OP_MAP.md`. Without the CLI sibling
//! the CLI half skips, and `VIPRS_REQUIRE_CLI=1` turns that skip into a
//! failure, the same discipline as every CLI differential cell.
//!
//! # What it deliberately does not do
//!
//! It does not judge whether a mapping is any good. `OP_MAP.md` naming a
//! function is enough to pass here; whether the command behaves like vips is
//! the differential cells' job. It reads `pub fn` lines from rustfmt'd source,
//! so a function generated by a macro is invisible to it. And modules marked
//! as reached through a built-in are accounted for as a whole: a new builder
//! setter on the engine is a flag question for `viprs pyramid`, not a missing
//! op, and this guard does not try to tell the two apart.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

mod common;
use common::cli::{cli_dir, require_cli};
use common::manifest;

// ---------------------------------------------------------------------------
// The tables. Data, reviewed like code: every row carries its reason.
// ---------------------------------------------------------------------------

/// How the CLI reaches one public core module.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Reach {
    /// An op family: every `pub fn` in the module is held to the `OP_MAP.md`
    /// section with this key (the `src/<key>.rs` its heading names).
    OpFamily(&'static str),
    /// Part of the codec surface: every load/save entry point in the module is
    /// held to `OP_MAP.md`'s foreign section.
    Codec,
    /// Reached through this built-in `viprs` command, which is not an op and
    /// so has no `OP_MAP.md` row. The command has to exist in the CLI.
    Builtin(&'static str),
    /// Nothing in the CLI reaches it, on purpose.
    NotApplicable,
}

/// One row of [`MODULES`].
struct ModuleRow {
    module: &'static str,
    reach: Reach,
    why: &'static str,
}

const fn row(module: &'static str, reach: Reach, why: &'static str) -> ModuleRow {
    ModuleRow { module, reach, why }
}

/// Every public core module, and how the CLI reaches it.
const MODULES: &[ModuleRow] = &[];

/// `(module, fn, reason)`: a function in an op-family or codec module that
/// `OP_MAP.md` does not name, and why it needs no `viprs` surface.
const FN_EXCLUSIONS: &[(&str, &str, &str)] = &[];

/// `(feature, reason)`: a core capability feature the CLI does not forward.
const CORE_FEATURES_NOT_IN_CLI: &[(&str, &str)] = &[];

/// The tables one check runs against. The real run uses the consts above; the
/// controls pass synthetic ones so they test the checker, not today's data.
struct Tables<'a> {
    modules: &'a [ModuleRow],
    fn_exclusions: &'a [(&'a str, &'a str, &'a str)],
    features_not_in_cli: &'a [(&'a str, &'a str)],
}

const REAL: Tables<'static> = Tables {
    modules: MODULES,
    fn_exclusions: FN_EXCLUSIONS,
    features_not_in_cli: CORE_FEATURES_NOT_IN_CLI,
};

// ---------------------------------------------------------------------------
// The two trees, read from disk.
// ---------------------------------------------------------------------------

/// What the guard needs from the core.
#[derive(Clone)]
struct Core {
    manifest: String,
    lib_rs: String,
    /// Source per declared module (a directory module is its files joined).
    modules: BTreeMap<String, String>,
}

/// What the guard needs from the CLI.
#[derive(Clone)]
struct Cli {
    manifest: String,
    features_rs: String,
    main_rs: String,
    op_map: String,
}

fn core_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../libviprs")
}

fn read(path: &Path) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()))
}

/// Every `.rs` file under `dir`, sorted, so a directory module reads the same
/// on every machine.
fn rust_files(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(d) = stack.pop() {
        let entries =
            std::fs::read_dir(&d).unwrap_or_else(|e| panic!("cannot list {}: {e}", d.display()));
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else if path.extension().is_some_and(|x| x == "rs") {
                out.push(path);
            }
        }
    }
    out.sort();
    out
}

fn load_core() -> Core {
    let dir = core_dir();
    let lib_rs = read(&dir.join("src/lib.rs"));
    let mut modules = BTreeMap::new();
    for (name, _) in declared_modules(&lib_rs) {
        let file = dir.join(format!("src/{name}.rs"));
        let sub = dir.join(format!("src/{name}"));
        let mut text = String::new();
        if file.is_file() {
            text.push_str(&read(&file));
        }
        if sub.is_dir() {
            for f in rust_files(&sub) {
                text.push('\n');
                text.push_str(&read(&f));
            }
        }
        modules.insert(name, text);
    }
    Core {
        manifest: read(&dir.join("Cargo.toml")),
        lib_rs,
        modules,
    }
}

/// Whether the CLI sources are on disk. A skip without `VIPRS_REQUIRE_CLI=1`,
/// a panic with it, exactly like `common::cli::cli_available`, except that a
/// pre-built `$VIPRS_BIN` does not count: this guard reads the CLI's source,
/// not its binary.
fn cli_source_available() -> bool {
    if cli_dir().join("Cargo.toml").is_file() {
        return true;
    }
    assert!(
        !require_cli(),
        "VIPRS_REQUIRE_CLI=1 but there is no libviprs-cli checkout at {}, so the \
         surface guard would skip and report a green that compared nothing",
        cli_dir().display()
    );
    eprintln!(
        "SKIP: no libviprs-cli checkout at {} (set $VIPRS_CLI_DIR)",
        cli_dir().display()
    );
    false
}

fn load_cli() -> Cli {
    let dir = cli_dir();
    Cli {
        manifest: read(&dir.join("Cargo.toml")),
        features_rs: read(&dir.join("src/features.rs")),
        main_rs: read(&dir.join("src/main.rs")),
        op_map: read(&dir.join("OP_MAP.md")),
    }
}

// ---------------------------------------------------------------------------
// Readers. Each one takes text so the controls can hand it a mutated copy.
// ---------------------------------------------------------------------------

/// `(module, is_pub)` for every `mod` item at the top of `lib.rs`.
///
/// `pub(crate) mod` and plain `mod` are declared but not public. They are
/// returned so a [`MODULES`] row for one is not mistaken for a stale row (the
/// core's `raster_ops` is `pub(crate)`, yet its `Raster` methods are public
/// and `OP_MAP.md` has a section for it).
fn declared_modules(lib_rs: &str) -> Vec<(String, bool)> {
    lib_rs
        .lines()
        .filter_map(|line| {
            let (rest, public) = if let Some(r) = line.strip_prefix("pub mod ") {
                (r, true)
            } else if let Some(r) = line.strip_prefix("pub(crate) mod ") {
                (r, false)
            } else {
                (line.strip_prefix("mod ")?, false)
            };
            let name = rest.strip_suffix(';')?.trim();
            is_ident(name).then(|| (name.to_string(), public))
        })
        .collect()
}

fn is_ident(s: &str) -> bool {
    !s.is_empty()
        && s.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
        && !s.starts_with(|c: char| c.is_ascii_digit())
}

/// Every `pub fn` name in `src`, free functions and methods alike, with test
/// code left out.
///
/// Relies on rustfmt layout: a `#[cfg(test)]` item ends at the first line that
/// is its own indentation followed by `}`. Visibility-restricted functions
/// (`pub(crate) fn`) are not public and are not returned.
fn pub_fns(src: &str) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let mut skip_until: Option<String> = None;
    let mut test_attr_indent: Option<String> = None;
    for line in src.lines() {
        if let Some(end) = &skip_until {
            if line == end {
                skip_until = None;
            }
            continue;
        }
        let trimmed = line.trim_start();
        let indent = &line[..line.len() - trimmed.len()];
        if trimmed.starts_with("#[cfg(test)]") || trimmed.starts_with("#[cfg(all(test") {
            test_attr_indent = Some(indent.to_string());
            continue;
        }
        if let Some(attr_indent) = test_attr_indent.take() {
            if trimmed.starts_with("#[") || trimmed.starts_with("///") {
                test_attr_indent = Some(attr_indent);
                continue;
            }
            if trimmed.trim_end().ends_with('{') {
                skip_until = Some(format!("{attr_indent}}}"));
            }
            continue;
        }
        let mut rest = match trimmed.strip_prefix("pub ") {
            Some(r) => r,
            None => continue,
        };
        for qualifier in ["const ", "unsafe ", "async ", "extern \"C\" "] {
            if let Some(r) = rest.strip_prefix(qualifier) {
                rest = r;
            }
        }
        if let Some(r) = rest.strip_prefix("fn ") {
            let name: String = r
                .chars()
                .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                .collect();
            if is_ident(&name) {
                out.insert(name);
            }
        }
    }
    out
}

/// `OP_MAP.md` split at its `## ` headings, keyed by the first `src/<x>.rs`
/// the heading names (`## colour (src/colour.rs: ...)` is `colour`), or by the
/// heading's first word when it names no source file (`## foreign (...)` is
/// `foreign`).
fn op_map_sections(op_map: &str) -> BTreeMap<String, String> {
    let mut out: BTreeMap<String, String> = BTreeMap::new();
    let mut key: Option<String> = None;
    for line in op_map.lines() {
        if let Some(heading) = line.strip_prefix("## ") {
            let from_src = heading.split("src/").nth(1).and_then(|r| {
                let name: String = r
                    .chars()
                    .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                    .collect();
                r[name.len()..].starts_with(".rs").then_some(name)
            });
            let k = from_src.unwrap_or_else(|| {
                heading
                    .split_whitespace()
                    .next()
                    .unwrap_or("")
                    .to_ascii_lowercase()
            });
            key = Some(k);
        }
        if let Some(k) = &key {
            let section = out.entry(k.clone()).or_default();
            section.push_str(line);
            section.push('\n');
        }
    }
    out
}

/// Every identifier inside backticks in `text`, with `a::with_{x, y}` brace
/// lists expanded, because that is how `OP_MAP.md` names a run of setters.
fn backtick_idents(text: &str) -> BTreeSet<String> {
    fn expand(s: &str) -> Vec<String> {
        let Some(open) = s.find('{') else {
            return vec![s.to_string()];
        };
        let Some(close) = s[open..].find('}').map(|c| open + c) else {
            return vec![s.to_string()];
        };
        let (head, alts, tail) = (&s[..open], &s[open + 1..close], &s[close + 1..]);
        alts.split(',')
            .flat_map(|alt| expand(&format!("{head}{}{tail}", alt.trim())))
            .collect()
    }
    let mut out = BTreeSet::new();
    for (i, chunk) in text.split('`').enumerate() {
        if i % 2 == 0 {
            continue;
        }
        for expanded in expand(&chunk.replace('\n', " ")) {
            let mut cur = String::new();
            for ch in expanded.chars().chain(std::iter::once(' ')) {
                if ch.is_ascii_alphanumeric() || ch == '_' {
                    cur.push(ch);
                } else if !cur.is_empty() {
                    if is_ident(&cur) {
                        out.insert(std::mem::take(&mut cur));
                    } else {
                        cur.clear();
                    }
                }
            }
        }
    }
    out
}

/// Whether `OP_MAP.md` names `function`, directly or through the dedup rules
/// its legend states: a `try_*` twin folds into its base, an option variant
/// (`x_with`, `x_with_profile`, ...) folds into `x` and `x` into a row that
/// only names `x_with`, `_filled` folds into the outline form, and a file
/// `save_x` is the same row as its `encode_x`.
fn named_in(function: &str, idents: &BTreeSet<String>) -> bool {
    let mut candidates = vec![function.to_string()];
    if let Some(base) = function.strip_prefix("try_") {
        candidates.push(base.to_string());
    }
    for c in candidates.clone() {
        if let Some(at) = c.find("_with") {
            candidates.push(c[..at].to_string());
        }
        if let Some(base) = c.strip_suffix("_filled") {
            candidates.push(base.to_string());
        }
        if let Some(base) = c.strip_prefix("save_") {
            candidates.push(format!("encode_{base}"));
        }
    }
    candidates.iter().any(|c| {
        idents.contains(c)
            || idents.iter().any(|id| {
                id.strip_prefix(c.as_str())
                    .is_some_and(|t| t.starts_with("_with"))
            })
    })
}

/// Whether a codec-module function is a load or save entry point, the only
/// shape the foreign section is about. Option setters and probes in those
/// modules are not, and the module's [`MODULES`] row covers them.
fn is_codec_entry_point(function: &str) -> bool {
    function.starts_with("decode")
        || function.starts_with("encode")
        || function.starts_with("save")
        || function.contains("load")
        || function.contains("save")
}

/// The built-in commands in the CLI's `enum Command`, kebab-cased the way
/// clap derives them (`TestImage` is `test-image`). The op families are
/// assembled elsewhere and are `OP_MAP.md`'s business, not this list's.
fn cli_builtins(main_rs: &str) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let mut inside = false;
    for line in main_rs.lines() {
        if line.starts_with("enum Command {") || line.starts_with("pub enum Command {") {
            inside = true;
            continue;
        }
        if !inside {
            continue;
        }
        if line == "}" {
            break;
        }
        let Some(rest) = line.strip_prefix("    ") else {
            continue;
        };
        if !rest.starts_with(|c: char| c.is_ascii_uppercase()) {
            continue;
        }
        let variant: String = rest
            .chars()
            .take_while(|c| c.is_ascii_alphanumeric())
            .collect();
        let mut kebab = String::new();
        for (i, ch) in variant.chars().enumerate() {
            if ch.is_ascii_uppercase() {
                if i > 0 {
                    kebab.push('-');
                }
                kebab.push(ch.to_ascii_lowercase());
            } else {
                kebab.push(ch);
            }
        }
        out.insert(kebab);
    }
    out
}

/// The names in the CLI's `FEATURES` table, which is what `viprs features`
/// prints (`("jxl", cfg!(feature = "jxl"))` rows).
fn cli_listed_features(features_rs: &str) -> BTreeSet<String> {
    features_rs
        .lines()
        .filter_map(|line| {
            let rest = line.trim().strip_prefix("(\"")?;
            let (name, tail) = rest.split_once('"')?;
            tail.contains("cfg!(feature").then(|| name.to_string())
        })
        .collect()
}

// ---------------------------------------------------------------------------
// The check.
// ---------------------------------------------------------------------------

/// Everything the CLI fails to account for, one line per item. Empty means
/// covered.
fn uncovered(core: &Core, cli: &Cli, t: &Tables) -> Vec<String> {
    let mut problems = Vec::new();
    feature_problems(core, cli, t, &mut problems);
    module_problems(core, cli, t, &mut problems);
    problems
}

fn feature_problems(core: &Core, cli: &Cli, t: &Tables, problems: &mut Vec<String>) {
    let core_features = manifest::feature_names(&core.manifest);
    let cli_features = manifest::features(&cli.manifest);
    let listed = cli_listed_features(&cli.features_rs);
    let core_table = manifest::features(&core.manifest);
    let forwarder =
        |feature: &str| manifest::forwarder(&cli_features, &core_table, feature, &["full"]);

    for feature in &core_features {
        let excluded = t.features_not_in_cli.iter().any(|(f, _)| f == feature);
        match forwarder(feature) {
            Some(cli_name) if excluded => problems.push(format!(
                "feature `{feature}`: CORE_FEATURES_NOT_IN_CLI excuses it, but the cli \
                 forwards it as `{cli_name}`. Drop the row."
            )),
            Some(cli_name) if !listed.contains(&cli_name) => problems.push(format!(
                "feature `{feature}`: the cli forwards it as `{cli_name}`, which \
                 `viprs features` does not list (src/features.rs FEATURES)"
            )),
            Some(_) => {}
            None if excluded => {}
            None => problems.push(format!(
                "feature `{feature}`: the core declares it and no libviprs-cli feature \
                 enables `libviprs/{feature}`. Forward it, or add a row to \
                 CORE_FEATURES_NOT_IN_CLI saying why the CLI has no use for it."
            )),
        }
    }
    for (feature, why) in t.features_not_in_cli {
        if !core_features.iter().any(|f| f == feature) {
            problems.push(format!(
                "feature `{feature}`: CORE_FEATURES_NOT_IN_CLI has a row for it ({why}) \
                 and the core no longer declares it. Drop or rename the row."
            ));
        }
        if why.trim().is_empty() {
            problems.push(format!(
                "feature `{feature}`: its CORE_FEATURES_NOT_IN_CLI row has no reason"
            ));
        }
    }
}

fn module_problems(core: &Core, cli: &Cli, t: &Tables, problems: &mut Vec<String>) {
    let declared = declared_modules(&core.lib_rs);
    let sections = op_map_sections(&cli.op_map);
    let builtins = cli_builtins(&cli.main_rs);
    let foreign = sections
        .get("foreign")
        .map(|s| backtick_idents(s))
        .unwrap_or_default();

    for (module, public) in &declared {
        if *public && !t.modules.iter().any(|r| r.module == module) {
            problems.push(format!(
                "module `{module}`: public in the core and MODULES says nothing about \
                 it. Add a row: its OP_MAP.md family, the codec surface, the built-in \
                 command that reaches it, or why nothing does."
            ));
        }
    }

    // Which (module, fn) pairs a scan actually looked at, so an exclusion row
    // for anything else is stale.
    let mut scanned: BTreeMap<&str, BTreeSet<String>> = BTreeMap::new();

    for r in t.modules {
        if !declared.iter().any(|(m, _)| m == r.module) {
            problems.push(format!(
                "module `{}`: MODULES has a row for it and the core's lib.rs declares \
                 no such module. Drop or rename the row.",
                r.module
            ));
            continue;
        }
        if r.why.trim().is_empty() {
            problems.push(format!(
                "module `{}`: its MODULES row has no reason",
                r.module
            ));
        }
        let src = core.modules.get(r.module).map(String::as_str).unwrap_or("");
        match r.reach {
            Reach::OpFamily(key) => {
                let Some(section) = sections.get(key) else {
                    problems.push(format!(
                        "module `{}`: MODULES points it at OP_MAP.md section `{key}`, and \
                         OP_MAP.md has no `## ... (src/{key}.rs ...)` heading",
                        r.module
                    ));
                    continue;
                };
                let idents = backtick_idents(section);
                let fns = pub_fns(src);
                for f in &fns {
                    check_fn(
                        r.module,
                        f,
                        named_in(f, &idents),
                        t,
                        problems,
                        "its OP_MAP.md family section",
                    );
                }
                scanned.insert(r.module, fns);
            }
            Reach::Codec => {
                let fns: BTreeSet<String> = pub_fns(src)
                    .into_iter()
                    .filter(|f| is_codec_entry_point(f))
                    .collect();
                for f in &fns {
                    check_fn(
                        r.module,
                        f,
                        named_in(f, &foreign),
                        t,
                        problems,
                        "OP_MAP.md's foreign section",
                    );
                }
                scanned.insert(r.module, fns);
            }
            Reach::Builtin(command) => {
                if !builtins.contains(command) {
                    problems.push(format!(
                        "module `{}`: MODULES says `viprs {command}` reaches it, and the \
                         cli's enum Command has no such built-in (has: {builtins:?})",
                        r.module
                    ));
                }
            }
            Reach::NotApplicable => {}
        }
    }

    for (module, function, why) in t.fn_exclusions {
        let Some(fns) = scanned.get(module) else {
            problems.push(format!(
                "`{module}::{function}`: FN_EXCLUSIONS has a row for it ({why}), and \
                 `{module}` is not a module this guard scans fn by fn (no OpFamily or \
                 Codec row). Drop the row."
            ));
            continue;
        };
        if !fns.contains(*function) {
            problems.push(format!(
                "`{module}::{function}`: FN_EXCLUSIONS has a row for it ({why}) and the \
                 core has no such function there any more. Drop or rename the row."
            ));
        }
        if why.trim().is_empty() {
            problems.push(format!(
                "`{module}::{function}`: its FN_EXCLUSIONS row has no reason"
            ));
        }
    }
}

fn check_fn(
    module: &str,
    function: &str,
    named: bool,
    t: &Tables,
    problems: &mut Vec<String>,
    held_to: &str,
) {
    let excluded = t
        .fn_exclusions
        .iter()
        .any(|(m, f, _)| *m == module && *f == function);
    if named && excluded {
        problems.push(format!(
            "`{module}::{function}`: FN_EXCLUSIONS excuses it, and {held_to} names it \
             after all. Drop the row."
        ));
    } else if !named && !excluded {
        problems.push(format!(
            "`{module}::{function}`: public in the core, and {held_to} does not name it. \
             Give it a viprs command and an OP_MAP.md row, or add an FN_EXCLUSIONS row \
             saying why it needs none."
        ));
    }
}

// ---------------------------------------------------------------------------
// The guard.
// ---------------------------------------------------------------------------

/// The real thing: today's core against today's CLI and today's tables.
#[test]
fn the_cli_accounts_for_every_capability_the_core_has() {
    if !cli_source_available() {
        return;
    }
    let core = load_core();
    let cli = load_cli();
    sanity(&core, &cli);
    let problems = uncovered(&core, &cli, &REAL);
    assert!(
        problems.is_empty(),
        "the core has {} thing(s) libviprs-cli does not account for:\n  {}",
        problems.len(),
        problems.join("\n  ")
    );
}

/// The readers find what is definitely there, so an empty problem list means
/// covered rather than "read nothing".
fn sanity(core: &Core, cli: &Cli) {
    let features = manifest::feature_names(&core.manifest);
    for want in ["pdfium", "packfile", "jxl"] {
        assert!(
            features.iter().any(|f| f == want),
            "positive control: the core's [features] should declare `{want}`, read {features:?}"
        );
    }
    let modules = declared_modules(&core.lib_rs);
    assert!(
        modules.iter().filter(|(_, p)| *p).count() >= 40
            && modules.iter().any(|(m, p)| m == "arithmetic" && *p),
        "positive control: lib.rs should declare dozens of public modules, arithmetic \
         among them, read {modules:?}"
    );
    let arith = pub_fns(
        core.modules
            .get("arithmetic")
            .map(String::as_str)
            .unwrap_or(""),
    );
    assert!(
        arith.len() >= 100,
        "positive control: arithmetic.rs has well over 100 pub fns, read {}",
        arith.len()
    );
    let sections = op_map_sections(&cli.op_map);
    for want in ["arithmetic", "colour", "foreign", "raster_ops"] {
        assert!(
            sections.contains_key(want),
            "positive control: OP_MAP.md should have a `{want}` section, read {:?}",
            sections.keys().collect::<Vec<_>>()
        );
    }
    let builtins = cli_builtins(&cli.main_rs);
    for want in ["pyramid", "features", "test-image"] {
        assert!(
            builtins.contains(want),
            "positive control: the cli's enum Command should have `{want}`, read {builtins:?}"
        );
    }
    let listed = cli_listed_features(&cli.features_rs);
    assert!(
        listed.contains("pdfium") && listed.contains("jxl"),
        "positive control: src/features.rs FEATURES should list pdfium and jxl, read {listed:?}"
    );
}

/// `viprs features --json` still speaks the version this guard reads its
/// `FEATURES` table as, and prints nothing that table lacks.
///
/// The guard reads the table rather than the binary because the binary only
/// prints what one build has. This test is what ties the two together: if
/// the output grows a `"v": 2`, someone has changed what the listing means,
/// and the guard has to be re-read before it is trusted again.
#[test]
fn viprs_features_json_is_the_shape_the_guard_reads() {
    if !cli_source_available() {
        return;
    }
    let out = common::cli::run_viprs(&["features", "--json"]);
    assert!(
        out.status.success(),
        "`viprs features --json` failed: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let json: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap_or_else(|e| {
        panic!(
            "`viprs features --json` printed something that is not JSON ({e}): {}",
            String::from_utf8_lossy(&out.stdout)
        )
    });
    assert_eq!(
        json["v"],
        serde_json::json!(1),
        "`viprs features --json` is no longer format version 1: {json}"
    );
    let listed = cli_listed_features(&load_cli().features_rs);
    let printed = json["features"]
        .as_array()
        .unwrap_or_else(|| panic!("`features` is not an array: {json}"));
    for name in printed {
        let name = name
            .as_str()
            .unwrap_or_else(|| panic!("a feature that is not a string: {json}"));
        assert!(
            listed.contains(name),
            "`viprs features --json` printed `{name}`, which src/features.rs FEATURES \
             does not list ({listed:?})"
        );
    }
}

// ---------------------------------------------------------------------------
// Controls. They run on today's core text, mutated, against small synthetic
// tables, so they test the checker whatever the real tables say.
// ---------------------------------------------------------------------------

/// A minimal CLI that covers nothing but what each control sets up.
fn synthetic_cli(op_map: &str) -> Cli {
    Cli {
        manifest: "[features]\nfull = [\"jxl\"]\njxl = [\"libviprs/jxl\"]\n".to_string(),
        features_rs: "const FEATURES: &[(&str, bool)] = &[\n    (\"jxl\", cfg!(feature = \"jxl\")),\n];\n"
            .to_string(),
        main_rs: "enum Command {\n    /// doc\n    Pyramid(Box<PyramidArgs>),\n    TestImage(TestImageArgs),\n}\n"
            .to_string(),
        op_map: op_map.to_string(),
    }
}

/// A core with exactly the pieces a control names: one op family, one codec
/// module, one built-in module, and the given features.
fn synthetic_core(features: &str, arithmetic: &str) -> Core {
    let lib_rs =
        "pub mod arithmetic;\npub mod gif;\npub mod engine;\npub(crate) mod hex;\n".to_string();
    let mut modules = BTreeMap::new();
    modules.insert("arithmetic".to_string(), arithmetic.to_string());
    modules.insert(
        "gif".to_string(),
        "pub fn decode_gif() {}\npub fn decode_gif_with() {}\nimpl O { pub fn with_dither(self) {} }\n"
            .to_string(),
    );
    modules.insert(
        "engine".to_string(),
        "pub fn generate_pyramid() {}\n".to_string(),
    );
    modules.insert("hex".to_string(), String::new());
    Core {
        manifest: format!("[features]\ndefault = []\n{features}"),
        lib_rs,
        modules,
    }
}

const SYNTH_OP_MAP: &str = "\
## arithmetic (src/arithmetic.rs: 2 pub fns)\n\
| `abs` | `abs` | S1 | EXACT | `try_abs` folds |\n\
## foreign (codec load/save)\n\
| `decode_gif_with` | `gifload` | EXACT | | |\n";

const SYNTH_MODULES: &[ModuleRow] = &[
    row(
        "arithmetic",
        Reach::OpFamily("arithmetic"),
        "the arithmetic family",
    ),
    row("gif", Reach::Codec, "the GIF codec"),
    row(
        "engine",
        Reach::Builtin("pyramid"),
        "viprs pyramid drives the engine",
    ),
    row(
        "hex",
        Reach::NotApplicable,
        "crate-private, listed to show a row may name one",
    ),
];

const SYNTH_ARITH: &str = "impl Raster {\n    pub fn abs(&self) {}\n    pub fn try_abs(&self) {}\n}\n\
#[cfg(test)]\nmod tests {\n    pub fn not_public_api() {}\n}\n";

fn synth_tables<'a>(
    fn_exclusions: &'a [(&'a str, &'a str, &'a str)],
    features_not_in_cli: &'a [(&'a str, &'a str)],
) -> Tables<'a> {
    Tables {
        modules: SYNTH_MODULES,
        fn_exclusions,
        features_not_in_cli,
    }
}

/// The synthetic baseline is covered, so every control below starts green and
/// the red it reports is the mutation's, not the scaffolding's.
#[test]
fn control_the_synthetic_baseline_is_covered() {
    let core = synthetic_core("jxl = [\"dep:x\"]\nserde = []\n", SYNTH_ARITH);
    let cli = synthetic_cli(SYNTH_OP_MAP);
    let t = synth_tables(&[], &[("serde", "derives only")]);
    assert_eq!(uncovered(&core, &cli, &t), Vec::<String>::new());
}

/// Positive control: a new `pub fn` in an op family turns the guard red and
/// names it, and taking it away turns it green again.
#[test]
fn control_a_new_pub_fn_in_an_op_family_is_red_until_removed() {
    let cli = synthetic_cli(SYNTH_OP_MAP);
    let t = synth_tables(&[], &[]);
    let grown = SYNTH_ARITH.replace(
        "    pub fn try_abs(&self) {}\n",
        "    pub fn try_abs(&self) {}\n    pub fn zz_synthetic_capability(&self) {}\n",
    );
    let red = uncovered(&synthetic_core("", &grown), &cli, &t);
    assert!(
        red.len() == 1 && red[0].contains("arithmetic::zz_synthetic_capability"),
        "a new op-family fn must be the one thing named, got {red:#?}"
    );
    let green = uncovered(&synthetic_core("", SYNTH_ARITH), &cli, &t);
    assert!(
        green.is_empty(),
        "removing it must turn green, got {green:#?}"
    );

    // The same on the real core text: arithmetic.rs as it is today plus one
    // function, against a section that names everything else in it.
    let real = load_core();
    let arith = real.modules.get("arithmetic").cloned().unwrap_or_default();
    let mut names: Vec<String> = pub_fns(&arith).into_iter().collect();
    names.sort();
    let section = format!(
        "## arithmetic (src/arithmetic.rs)\n{}\n## foreign\n| `decode_gif_with` |\n",
        names
            .iter()
            .map(|n| format!("`{n}`"))
            .collect::<Vec<_>>()
            .join(" ")
    );
    let cli = synthetic_cli(&section);
    let base = uncovered(&synthetic_core("", &arith), &cli, &t);
    assert!(
        base.is_empty(),
        "today's arithmetic.rs against its own names: {base:#?}"
    );
    let grown =
        format!("{arith}\nimpl Raster {{\n    pub fn zz_synthetic_capability(&self) {{}}\n}}\n");
    let red = uncovered(&synthetic_core("", &grown), &cli, &t);
    assert!(
        red.len() == 1 && red[0].contains("zz_synthetic_capability"),
        "a dummy pub fn added to today's arithmetic.rs must be named, got {red:#?}"
    );
}

/// Positive control: a new codec entry point, a new public module and a new
/// capability feature are each red and named.
#[test]
fn control_a_new_codec_module_or_feature_is_red() {
    let cli = synthetic_cli(SYNTH_OP_MAP);
    let t = synth_tables(&[], &[]);

    let mut core = synthetic_core("", SYNTH_ARITH);
    core.modules
        .get_mut("gif")
        .unwrap()
        .push_str("pub fn save_gif_animated() {}\n");
    let red = uncovered(&core, &cli, &t);
    assert!(
        red.len() == 1 && red[0].contains("gif::save_gif_animated"),
        "a new codec entry point must be named, got {red:#?}"
    );

    let mut core = synthetic_core("", SYNTH_ARITH);
    core.lib_rs.push_str("pub mod zz_synthetic;\n");
    core.modules
        .insert("zz_synthetic".into(), "pub fn op() {}\n".into());
    let red = uncovered(&core, &cli, &t);
    assert!(
        red.len() == 1 && red[0].contains("module `zz_synthetic`"),
        "a new public module must be named, got {red:#?}"
    );

    let core = synthetic_core("zz-synthetic = [\"dep:x\"]\n", SYNTH_ARITH);
    let red = uncovered(&core, &cli, &t);
    assert!(
        red.len() == 1 && red[0].contains("feature `zz-synthetic`"),
        "a new core feature must be named, got {red:#?}"
    );

    // And on the real manifest: today's core features plus one.
    let real = load_core();
    let real_cli_features: Vec<String> = manifest::feature_names(&real.manifest);
    let fwd: String = real_cli_features
        .iter()
        .map(|f| format!("{f} = [\"libviprs/{f}\"]\n"))
        .collect();
    let listed: String = real_cli_features
        .iter()
        .map(|f| format!("    (\"{f}\", cfg!(feature = \"{f}\")),\n"))
        .collect();
    let mut cli = synthetic_cli(SYNTH_OP_MAP);
    cli.manifest = format!("[features]\n{fwd}");
    cli.features_rs = format!("const FEATURES: &[(&str, bool)] = &[\n{listed}];\n");
    let mut core = synthetic_core("", SYNTH_ARITH);
    core.manifest = real.manifest.clone();
    assert!(uncovered(&core, &cli, &t).is_empty());
    core.manifest = real
        .manifest
        .replacen("[features]\n", "[features]\nzz-synthetic = []\n", 1);
    let red = uncovered(&core, &cli, &t);
    assert!(
        red.len() == 1 && red[0].contains("feature `zz-synthetic`"),
        "a feature added to today's core manifest must be named, got {red:#?}"
    );
}

/// Negative control: renaming an excluded item without updating the list is
/// red, so the list cannot rot into rows that excuse nothing.
#[test]
fn control_a_renamed_excluded_item_is_red() {
    let cli = synthetic_cli(SYNTH_OP_MAP);

    // A module row whose module was renamed: the stale row and the new,
    // unaccounted module are both named.
    let core = synthetic_core("", SYNTH_ARITH);
    let mut renamed = core.clone();
    renamed.lib_rs = renamed
        .lib_rs
        .replace("pub mod engine;", "pub mod engine2;");
    renamed.modules.insert("engine2".into(), String::new());
    let red = uncovered(&renamed, &cli, &synth_tables(&[], &[]));
    assert!(
        red.iter()
            .any(|p| p.contains("module `engine`") && p.contains("no such module"))
            && red.iter().any(|p| p.contains("module `engine2`")),
        "a renamed module must name the stale row and the new module, got {red:#?}"
    );

    // A feature exclusion whose feature was renamed.
    let core = synthetic_core("serde-derive = []\n", SYNTH_ARITH);
    let red = uncovered(
        &core,
        &cli,
        &synth_tables(&[], &[("serde", "derives only")]),
    );
    assert!(
        red.iter()
            .any(|p| p.contains("feature `serde`") && p.contains("no longer declares"))
            && red.iter().any(|p| p.contains("feature `serde-derive`")),
        "a renamed feature must name the stale row and the new feature, got {red:#?}"
    );

    // A fn exclusion whose fn was renamed.
    let arith = SYNTH_ARITH.replace(
        "    pub fn try_abs(&self) {}\n",
        "    pub fn try_abs(&self) {}\n    pub fn helper2(&self) {}\n",
    );
    let core = synthetic_core("", &arith);
    let red = uncovered(
        &core,
        &cli,
        &synth_tables(&[("arithmetic", "helper", "internal")], &[]),
    );
    assert!(
        red.iter()
            .any(|p| p.contains("arithmetic::helper`") && p.contains("no such function"))
            && red.iter().any(|p| p.contains("arithmetic::helper2")),
        "a renamed fn must name the stale row and the new fn, got {red:#?}"
    );

    // An exclusion for something the CLI covers after all is red too.
    let core = synthetic_core("jxl = [\"dep:x\"]\n", SYNTH_ARITH);
    let red = uncovered(
        &core,
        &cli,
        &synth_tables(&[("arithmetic", "abs", "x")], &[("jxl", "y")]),
    );
    assert!(
        red.iter()
            .any(|p| p.contains("arithmetic::abs") && p.contains("Drop the row"))
            && red
                .iter()
                .any(|p| p.contains("feature `jxl`") && p.contains("Drop the row")),
        "an exclusion for a covered item must be red, got {red:#?}"
    );
}

/// The readers parse the shapes they will meet.
#[test]
fn control_the_readers_read_what_they_say() {
    // pub fns: methods and free fns, qualifiers, no pub(crate), no test code.
    let src = "pub fn a() {}\npub(crate) fn b() {}\nimpl X {\n    pub const fn c() {}\n    pub unsafe fn d() {}\n    fn e() {}\n    #[cfg(test)]\n    pub fn f() {}\n}\n#[cfg(test)]\nmod tests {\n    pub fn g() {}\n}\npub fn h<T>(t: T) {}\n";
    let got: Vec<String> = pub_fns(src).into_iter().collect();
    assert_eq!(got, ["a", "c", "d", "h"]);

    // Brace lists expand; prose outside backticks does not count.
    let ids = backtick_idents("`AffineOptions::with_{odx,\nody}` and `x` but not y");
    assert!(ids.contains("with_odx") && ids.contains("with_ody") && ids.contains("x"));
    assert!(!ids.contains("y"));

    // Folds the OP_MAP legend states, and nothing broader.
    let ids: BTreeSet<String> = ["abs", "decode_gif_with", "encode_png", "draw_rect"]
        .into_iter()
        .map(String::from)
        .collect();
    for yes in [
        "try_abs",
        "abs_with",
        "decode_gif",
        "save_png",
        "draw_rect_filled",
    ] {
        assert!(named_in(yes, &ids), "{yes} should fold into a named row");
    }
    for no in ["absolute", "decode", "encode_jpeg", "zz_abs"] {
        assert!(!named_in(no, &ids), "{no} must not fold into a named row");
    }

    // Built-ins kebab-case; features read from the FEATURES rows only.
    let cli = synthetic_cli("");
    let builtins: Vec<String> = cli_builtins(&cli.main_rs).into_iter().collect();
    assert_eq!(builtins, ["pyramid", "test-image"]);
    let listed: Vec<String> = cli_listed_features(&cli.features_rs).into_iter().collect();
    assert_eq!(listed, ["jxl"]);

    // A multi-line feature array reads whole.
    let m = "[package]\nname = \"x\"\n[features]\ndefault = [\"a\"]\nfull = [\n    \"a\", # c\n    \"b\",\n]\na = [\"libviprs/a\"] # trailing\n[dependencies]\nz = \"1\"\n";
    let fs = manifest::features(m);
    let names: Vec<&str> = fs.iter().map(|f| f.name.as_str()).collect();
    assert_eq!(names, ["default", "full", "a"]);
    assert_eq!(fs[1].enables, ["a", "b"]);
    assert_eq!(fs[2].enables, ["libviprs/a"]);

    // A pure core alias is reached through what it aliases; anything else
    // has to be forwarded by name.
    let core = manifest::features(
        "[features]\nosink = []\ns3 = [\"osink\"]\npdfium = [\"dep:p\"]\npdfium-static = [\"pdfium\", \"p/static\"]\n",
    );
    let ours = manifest::features(
        "[features]\nfull = [\"libviprs/pdfium-static\"]\nosink = [\"libviprs/osink\"]\ns3 = [\"osink\"]\npdfium = [\"libviprs/pdfium\"]\n",
    );
    let fwd = |f: &str| manifest::forwarder(&ours, &core, f, &["full"]);
    assert_eq!(fwd("osink").as_deref(), Some("osink"));
    assert_eq!(fwd("s3").as_deref(), Some("osink"));
    assert_eq!(fwd("pdfium").as_deref(), Some("pdfium"));
    assert_eq!(
        fwd("pdfium-static"),
        None,
        "a bundle does not count, and pdfium-static is no alias"
    );
}
