//! CLI-DIFFERENTIAL suite — extract / geometry-placement family (a per-family
//! Wave-2 lane, CLI_CONTRACT.md §7, OP_MAP.md extract section).
//!
//! Each test runs `viprs <op> …` on the COMMON committed inputs under
//! `tests/fixtures/cli/extract/` and decode-compares its output against the
//! COMMITTED vips 8.18.4 reference at the op's §5 tolerance. The suite NEVER
//! runs vips: references are generated offline by `tools/gen_cli_expected.sh`
//! and committed. This cell copies the bands / morphology differential cells
//! exactly — including the skip-guard / `VIPRS_REQUIRE_CLI` discipline.
//!
//! Every extract op is oracle class **EXACT** (integer-in / integer-out,
//! decode-compare tol 0) **except `smartcrop --interesting entropy`**, which is
//! **GOLDEN-ONLY**: vips's entropy strategy makes a DIFFERENT discrete
//! crop-window choice than the core on the small committed input (measured
//! max-abs-diff 136 — a wholesale different region, not a tolerance), so there
//! is no meaningful cross-oracle. That reference is generated by `viprs` itself
//! (the strategy is deterministic across runs) and the test is a regression pin
//! that SAYS SO (CLI_CONTRACT.md §5 GOLDEN-ONLY). Every other strategy —
//! `centre`/`low`/`high` (pure geometry) and `attention` (the saliency pipeline,
//! which lands on the vips pixel and crops a region distinct from low/high) — is
//! a genuine EXACT vips differential.
//!
//! Every reference is an integer uchar raster with a clean interpretation
//! (1-band, or sRGB-tagged 3-band), so all outputs round-trip losslessly through
//! PNG (no b-w-multiband promotion, no ≥5-band carrier).
//!
//! If the `libviprs-cli` sibling is not checked out (the default CI `test` job
//! and the Docker gate clone only the core counterpart), every test SKIPS with a
//! clear message rather than failing — the dedicated `cli-differential` CI job
//! lays the CLI down and actually exercises these (CLI_CONTRACT.md §7).

mod common;

use std::path::PathBuf;
use std::sync::OnceLock;

use common::cli::{cli_available, cli_fixture, decode_compare, run_viprs, run_viprs_ok};

use tempfile::TempDir;

/// EXACT oracle class: bit-exact decode comparison (CLI_CONTRACT.md §5). Every
/// extract op is integer-in / integer-out — including `smartcrop attention`.
const EXACT: f64 = 0.0;

/// GOLDEN-ONLY pin tolerance for `smartcrop --interesting entropy`: bit-exact
/// against a committed `viprs`-generated reference (NOT vips — no cross-oracle;
/// see the module header). A regression pin, not a cross-implementation check.
const GOLDEN: f64 = 0.0;

/// Skip-guard: `true` (with a printed reason) when the CLI sibling is absent.
///
/// When `$VIPRS_REQUIRE_CLI=1` (the dedicated `cli-differential` CI job) an
/// absent sibling instead PANICS inside [`cli_available`], so this never returns
/// `true` there — a would-be silent skip becomes a hard failure.
fn skip_if_no_cli(test: &str) -> bool {
    if cli_available() {
        return false;
    }
    eprintln!(
        "SKIP {test}: libviprs-cli sibling not checked out \
         (set $VIPRS_CLI_DIR / $VIPRS_BIN, or run in the cli-differential job)."
    );
    true
}

/// Absolute path to a fresh output file inside a **process-lifetime** temp dir
/// (one [`TempDir`] reused for every case, reclaimed at process exit).
fn out_path(name: &str) -> PathBuf {
    static DIR: OnceLock<TempDir> = OnceLock::new();
    let dir = DIR.get_or_init(|| tempfile::tempdir().expect("create temp dir"));
    dir.path().join(name)
}

// Common committed inputs (tests/fixtures/cli/extract/).
const RGB: &str = "extract/rgb.png";
const GRAY: &str = "extract/gray.png";
const SUB: &str = "extract/sub.png";

/// Convenience: the absolute string path of a committed fixture.
fn fx(rel: &str) -> String {
    cli_fixture(rel).to_str().unwrap().to_string()
}

// ---------------------------------------------------------------------------
// extract_area / crop — S1 rectangle copy. `crop` is a vips-callable ALIAS of
// extract_area dispatching to the same handler; a separate `vips crop` reference
// proves the alias command actually runs (not just that the handler is shared).
// ---------------------------------------------------------------------------

#[test]
fn extract_area_matches_vips_exact() {
    if skip_if_no_cli("extract_area") {
        return;
    }
    let out = out_path("extract_area.png");
    run_viprs_ok(&[
        "extract_area",
        &fx(RGB),
        out.to_str().unwrap(),
        "3",
        "4",
        "5",
        "6",
    ]);
    decode_compare(
        &out,
        &cli_fixture("extract/extract_area_expected.png"),
        EXACT,
    );
}

#[test]
fn crop_alias_matches_vips_exact() {
    if skip_if_no_cli("crop") {
        return;
    }
    let out = out_path("crop.png");
    run_viprs_ok(&["crop", &fx(RGB), out.to_str().unwrap(), "3", "4", "5", "6"]);
    decode_compare(&out, &cli_fixture("extract/crop_expected.png"), EXACT);
}

// ---------------------------------------------------------------------------
// embed — S1: black fill, the copy extend enum, and the background vector path.
// ---------------------------------------------------------------------------

#[test]
fn embed_black_matches_vips_exact() {
    if skip_if_no_cli("embed_black") {
        return;
    }
    let out = out_path("embed_black.png");
    run_viprs_ok(&[
        "embed",
        &fx(RGB),
        out.to_str().unwrap(),
        "2",
        "3",
        "24",
        "24",
    ]);
    decode_compare(
        &out,
        &cli_fixture("extract/embed_black_expected.png"),
        EXACT,
    );
}

#[test]
fn embed_copy_extend_matches_vips_exact() {
    if skip_if_no_cli("embed_copy") {
        return;
    }
    let out = out_path("embed_copy.png");
    // `--extend copy` replicates edge pixels — a distinct enum path from black.
    run_viprs_ok(&[
        "embed",
        &fx(RGB),
        out.to_str().unwrap(),
        "2",
        "3",
        "24",
        "24",
        "--extend",
        "copy",
    ]);
    decode_compare(&out, &cli_fixture("extract/embed_copy_expected.png"), EXACT);
}

#[test]
fn embed_background_vector_matches_vips_exact() {
    if skip_if_no_cli("embed_bg") {
        return;
    }
    let out = out_path("embed_bg.png");
    // `--extend background --background 128` exercises the vector-fill path.
    run_viprs_ok(&[
        "embed",
        &fx(GRAY),
        out.to_str().unwrap(),
        "1",
        "1",
        "8",
        "8",
        "--extend",
        "background",
        "--background",
        "128",
    ]);
    decode_compare(&out, &cli_fixture("extract/embed_bg_expected.png"), EXACT);
}

// ---------------------------------------------------------------------------
// gravity — S1: centre + a dash-spelled corner (south-east) exercising the
// VipsCompassDirection enum.
// ---------------------------------------------------------------------------

#[test]
fn gravity_centre_matches_vips_exact() {
    if skip_if_no_cli("gravity_centre") {
        return;
    }
    let out = out_path("gravity_centre.png");
    run_viprs_ok(&[
        "gravity",
        &fx(RGB),
        out.to_str().unwrap(),
        "centre",
        "24",
        "24",
    ]);
    decode_compare(
        &out,
        &cli_fixture("extract/gravity_centre_expected.png"),
        EXACT,
    );
}

#[test]
fn gravity_south_east_matches_vips_exact() {
    if skip_if_no_cli("gravity_se") {
        return;
    }
    let out = out_path("gravity_se.png");
    run_viprs_ok(&[
        "gravity",
        &fx(RGB),
        out.to_str().unwrap(),
        "south-east",
        "24",
        "24",
    ]);
    decode_compare(&out, &cli_fixture("extract/gravity_se_expected.png"), EXACT);
}

// ---------------------------------------------------------------------------
// replicate / zoom / subsample — S1 integer geometry.
// ---------------------------------------------------------------------------

#[test]
fn replicate_matches_vips_exact() {
    if skip_if_no_cli("replicate") {
        return;
    }
    let out = out_path("replicate.png");
    run_viprs_ok(&["replicate", &fx(RGB), out.to_str().unwrap(), "2", "3"]);
    decode_compare(&out, &cli_fixture("extract/replicate_expected.png"), EXACT);
}

#[test]
fn zoom_matches_vips_exact() {
    if skip_if_no_cli("zoom") {
        return;
    }
    let out = out_path("zoom.png");
    run_viprs_ok(&["zoom", &fx(GRAY), out.to_str().unwrap(), "3", "2"]);
    decode_compare(&out, &cli_fixture("extract/zoom_expected.png"), EXACT);
}

#[test]
fn subsample_matches_vips_exact() {
    if skip_if_no_cli("subsample") {
        return;
    }
    let out = out_path("subsample.png");
    // The core point-samples the top-left of each cell; vips's default
    // (point=false) agrees exactly on this input.
    run_viprs_ok(&["subsample", &fx(RGB), out.to_str().unwrap(), "2", "2"]);
    decode_compare(&out, &cli_fixture("extract/subsample_expected.png"), EXACT);
}

// ---------------------------------------------------------------------------
// insert — S2 (two fixed inputs): non-expand (main-sized) + expand (the canvas
// grows to the bounding box, 19x19, when the sub overhangs the main).
// ---------------------------------------------------------------------------

#[test]
fn insert_matches_vips_exact() {
    if skip_if_no_cli("insert") {
        return;
    }
    let out = out_path("insert.png");
    run_viprs_ok(&[
        "insert",
        &fx(RGB),
        &fx(SUB),
        out.to_str().unwrap(),
        "4",
        "5",
    ]);
    decode_compare(&out, &cli_fixture("extract/insert_expected.png"), EXACT);
}

#[test]
fn insert_expand_matches_vips_exact() {
    if skip_if_no_cli("insert_expand") {
        return;
    }
    let out = out_path("insert_expand.png");
    // Placing the 6x6 sub at (13,13) overhangs the 16x16 main, so `--expand`
    // grows the canvas to the 19x19 bounding box (uncovered pixels black).
    run_viprs_ok(&[
        "insert",
        &fx(RGB),
        &fx(SUB),
        out.to_str().unwrap(),
        "13",
        "13",
        "--expand",
    ]);
    decode_compare(
        &out,
        &cli_fixture("extract/insert_expand_expected.png"),
        EXACT,
    );
}

// ---------------------------------------------------------------------------
// smartcrop — S1: centre/low/high (pure geometry) + attention (the saliency
// pipeline) are EXACT vips differentials. `entropy` is GOLDEN-ONLY (see below).
// ---------------------------------------------------------------------------

#[test]
fn smartcrop_centre_matches_vips_exact() {
    if skip_if_no_cli("smartcrop_centre") {
        return;
    }
    let out = out_path("smartcrop_centre.png");
    run_viprs_ok(&[
        "smartcrop",
        &fx(RGB),
        out.to_str().unwrap(),
        "8",
        "8",
        "--interesting",
        "centre",
    ]);
    decode_compare(
        &out,
        &cli_fixture("extract/smartcrop_centre_expected.png"),
        EXACT,
    );
}

#[test]
fn smartcrop_low_matches_vips_exact() {
    if skip_if_no_cli("smartcrop_low") {
        return;
    }
    let out = out_path("smartcrop_low.png");
    run_viprs_ok(&[
        "smartcrop",
        &fx(RGB),
        out.to_str().unwrap(),
        "8",
        "8",
        "--interesting",
        "low",
    ]);
    decode_compare(
        &out,
        &cli_fixture("extract/smartcrop_low_expected.png"),
        EXACT,
    );
}

#[test]
fn smartcrop_high_matches_vips_exact() {
    if skip_if_no_cli("smartcrop_high") {
        return;
    }
    let out = out_path("smartcrop_high.png");
    run_viprs_ok(&[
        "smartcrop",
        &fx(RGB),
        out.to_str().unwrap(),
        "8",
        "8",
        "--interesting",
        "high",
    ]);
    decode_compare(
        &out,
        &cli_fixture("extract/smartcrop_high_expected.png"),
        EXACT,
    );
}

#[test]
fn smartcrop_attention_matches_vips_exact() {
    if skip_if_no_cli("smartcrop_attention") {
        return;
    }
    let out = out_path("smartcrop_attention.png");
    // The attention pipeline (lanczos3 shrink → edge/skin/saturation saliency →
    // gaussblur → argmax) lands on the vips pixel and crops region (15,11),
    // DISTINCT from low/high's (0,0) — a non-vacuous EXACT differential.
    run_viprs_ok(&[
        "smartcrop",
        &fx(RGB),
        out.to_str().unwrap(),
        "8",
        "8",
        "--interesting",
        "attention",
    ]);
    decode_compare(
        &out,
        &cli_fixture("extract/smartcrop_attention_expected.png"),
        EXACT,
    );
}

// ---------------------------------------------------------------------------
// smartcrop entropy — GOLDEN-ONLY regression pin (NO vips oracle).
//
// vips's `smartcrop --interesting entropy` picks a DIFFERENT discrete crop
// window than the core on this input (measured max-abs-diff 136 — a wholesale
// different region, not a tolerance), so there is nothing to cross-check
// against. The reference `smartcrop_entropy_golden.png` was generated by `viprs`
// itself (the strategy is deterministic across runs), and this test pins that
// output so a future regression in the entropy slicing loop fails loudly. It is
// NOT a vips differential (CLI_CONTRACT.md §5 GOLDEN-ONLY).
// ---------------------------------------------------------------------------

#[test]
fn smartcrop_entropy_golden_pin() {
    if skip_if_no_cli("smartcrop_entropy") {
        return;
    }
    let out = out_path("smartcrop_entropy.png");
    run_viprs_ok(&[
        "smartcrop",
        &fx(RGB),
        out.to_str().unwrap(),
        "8",
        "8",
        "--interesting",
        "entropy",
    ]);
    // GOLDEN-ONLY: compared against a committed viprs-generated reference, not
    // vips — there is no cross-oracle for this strategy on this input.
    decode_compare(
        &out,
        &cli_fixture("extract/smartcrop_entropy_golden.png"),
        GOLDEN,
    );
}

// ---------------------------------------------------------------------------
// Error paths (CLI_CONTRACT.md §8): a bad op input is a nonzero exit + a
// viprs-side message substring, never a panic/abort and never vips stderr text.
// ---------------------------------------------------------------------------

#[test]
fn extract_area_out_of_bounds_is_a_clean_error() {
    if skip_if_no_cli("extract_area_oob") {
        return;
    }
    let out = out_path("extract_area_oob.png");
    // A 20x20 rectangle at (10,10) does not fit the 16x16 input.
    let res = run_viprs(&[
        "extract_area",
        &fx(RGB),
        out.to_str().unwrap(),
        "10",
        "10",
        "20",
        "20",
    ]);
    assert!(
        !res.status.success(),
        "an out-of-bounds extract_area must exit nonzero"
    );
    let stderr = String::from_utf8_lossy(&res.stderr);
    assert!(
        stderr.contains("out of bounds"),
        "expected a viprs-side out-of-bounds message, got stderr: {stderr}"
    );
}

#[test]
fn extract_area_negative_coord_is_a_clean_error() {
    if skip_if_no_cli("extract_area_neg") {
        return;
    }
    let out = out_path("extract_area_neg.png");
    // vips's LEFT admits the signed gint range at parse; the core geometry is
    // u32-only, so a negative coordinate is a typed exit-1 error — NEVER a
    // u32::try_from abort (CLI_CONTRACT.md §8).
    let res = run_viprs(&[
        "extract_area",
        &fx(RGB),
        out.to_str().unwrap(),
        "-1",
        "0",
        "2",
        "2",
    ]);
    assert!(
        !res.status.success(),
        "a negative extract_area coordinate must exit nonzero"
    );
    let stderr = String::from_utf8_lossy(&res.stderr);
    assert!(
        stderr.contains("must be >= 0"),
        "expected a viprs-side negative-coordinate message, got stderr: {stderr}"
    );
}
