//! Integration tests: Google Maps layout with --centre support.
//!
//! Tests verify that the Google layout produces power-of-2 tile grids,
//! `{z}/{x}/{y}.ext` paths, no DZI manifest, and correct centre offsets.
//!
//! Expected fixtures were generated by libvips (vips 8.14.1) with:
//!   vips dzsave extracted_blueprint_portrait.png blueprint_portrait_google_centre \
//!     --layout google --tile-size 256 --overlap 0 --centre --suffix .png --strip
//!
//! Comparison uses decoded pixels. vips omits blank tiles, so for tiles
//! vips didn't emit, tests verify libviprs produces blank (background-only) tiles.

use std::collections::HashSet;
use std::path::Path;

use libviprs::{
    EngineConfig, FsSink, Layout, MemorySink, PyramidPlanner, TileFormat, extract_page_image,
    generate_pyramid,
};

const FIXTURE_PDF_PORTRAIT: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/blueprint-portrait.pdf"
);

const FIXTURE_PDF_MIX: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/blueprint-mix.pdf"
);

const FIXTURE_PDF_BLUEPRINT: &str =
    concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/blueprint.pdf");

const EXPECTED_PORTRAIT_GOOGLE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/blueprint_portrait_google_centre"
);

const EXPECTED_MIX_GOOGLE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/blueprint_mix_google_centre"
);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn collect_files(dir: &Path, ext: &str) -> Vec<(String, Vec<u8>)> {
    let mut files = Vec::new();
    collect_files_recursive(dir, dir, ext, &mut files);
    files.sort_by(|a, b| a.0.cmp(&b.0));
    files
}

fn collect_files_recursive(root: &Path, dir: &Path, ext: &str, out: &mut Vec<(String, Vec<u8>)>) {
    if !dir.is_dir() {
        return;
    }
    for entry in std::fs::read_dir(dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.is_dir() {
            collect_files_recursive(root, &path, ext, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some(ext) {
            let rel = path
                .strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .to_string();
            let bytes = std::fs::read(&path).unwrap();
            out.push((rel, bytes));
        }
    }
}

fn decode_png(data: &[u8]) -> (u32, u32, Vec<u8>) {
    let img = image::load_from_memory_with_format(data, image::ImageFormat::Png)
        .expect("failed to decode PNG");
    let w = img.width();
    let h = img.height();
    let raw = img.into_bytes();
    (w, h, raw)
}

fn load_portrait_raster() -> libviprs::Raster {
    extract_page_image(Path::new(FIXTURE_PDF_PORTRAIT), 1)
        .expect("failed to extract image from blueprint-portrait.pdf")
}

fn load_blueprint_raster() -> libviprs::Raster {
    extract_page_image(Path::new(FIXTURE_PDF_BLUEPRINT), 1)
        .expect("failed to extract image from blueprint.pdf")
}

fn load_mix_raster() -> libviprs::Raster {
    extract_page_image(Path::new(FIXTURE_PDF_MIX), 1)
        .expect("failed to extract image from blueprint-mix.pdf")
}

// ---------------------------------------------------------------------------
// Google layout structural tests (portrait PDF — extracted raster 3300x5024)
// ---------------------------------------------------------------------------

/// Verify that Google layout produces the correct number of levels and canvas
/// for the portrait PDF's extracted raster dimensions.
#[test]
fn google_centre_portrait_plan_structure() {
    let raster = load_portrait_raster();
    assert_eq!(raster.width(), 3300);
    assert_eq!(raster.height(), 5024);

    let planner = PyramidPlanner::new(3300, 5024, 256, 0, Layout::Google)
        .unwrap()
        .with_centre(true);
    let plan = planner.plan();

    // max(ceil(3300/256), ceil(5024/256)) = max(13, 20) = 20
    // n_levels = ceil(log2(20)) + 1 = 5 + 1 = 6
    assert_eq!(plan.level_count(), 6);

    // Canvas = 256 * 2^5 = 8192
    assert_eq!(plan.canvas_width, 8192);
    assert_eq!(plan.canvas_height, 8192);

    // Centre offsets
    assert_eq!(plan.centre_offset_x, (8192 - 3300) / 2); // 2446
    assert_eq!(plan.centre_offset_y, (8192 - 5024) / 2); // 1584

    // Power-of-2 grids
    for (i, level) in plan.levels.iter().enumerate() {
        let expected_grid = 1u32 << i;
        assert_eq!(level.cols, expected_grid, "Level {} cols", i);
        assert_eq!(level.rows, expected_grid, "Level {} rows", i);
    }

    // No DZI manifest
    assert!(plan.dzi_manifest("png").is_none());

    // Total tiles: 1 + 4 + 16 + 64 + 256 + 1024 = 1365
    assert_eq!(plan.total_tile_count(), 1365);
}

/// Generate Google+centre pyramid from portrait raster and verify every tile
/// is the correct dimensions and all expected coordinates are present.
#[test]
fn google_centre_portrait_generates_all_tiles() {
    let raster = load_portrait_raster();
    let planner = PyramidPlanner::new(raster.width(), raster.height(), 256, 0, Layout::Google)
        .unwrap()
        .with_centre(true);
    let plan = planner.plan();
    let sink = MemorySink::new();
    let config = EngineConfig::default();

    let result = generate_pyramid(&raster, &plan, &sink, &config).unwrap();
    assert_eq!(result.tiles_produced, plan.total_tile_count());

    // Every tile should be 256x256
    for tile in sink.tiles() {
        assert_eq!(tile.width, 256, "Tile {:?} wrong width", tile.coord);
        assert_eq!(tile.height, 256, "Tile {:?} wrong height", tile.coord);
    }
}

/// Generate to filesystem and verify path format is {z}/{x}/{y}.png.
#[test]
fn google_centre_portrait_path_format() {
    let raster = load_portrait_raster();
    let planner = PyramidPlanner::new(raster.width(), raster.height(), 256, 0, Layout::Google)
        .unwrap()
        .with_centre(true);
    let plan = planner.plan();

    let dir = tempfile::tempdir().unwrap();
    let base = dir.path().join("portrait_google");
    let sink = FsSink::new(base.clone(), plan.clone(), TileFormat::Png);

    generate_pyramid(&raster, &plan, &sink, &EngineConfig::default()).unwrap();

    let files = collect_files(&base, "png");
    assert_eq!(files.len() as u64, plan.total_tile_count());

    // All paths should match {z}/{x}/{y}.png format
    for (path, _) in &files {
        let parts: Vec<&str> = path.split('/').collect();
        assert_eq!(parts.len(), 3, "Bad path format: {path}");
        assert!(parts[2].ends_with(".png"), "Missing .png extension: {path}");
    }

    // No DZI manifest should exist
    assert!(!dir.path().join("portrait_google.dzi").exists());
}

/// Concurrent generation matches single-threaded output.
#[test]
fn google_centre_portrait_concurrent_matches() {
    let raster = load_portrait_raster();
    let planner = PyramidPlanner::new(raster.width(), raster.height(), 256, 0, Layout::Google)
        .unwrap()
        .with_centre(true);
    let plan = planner.plan();

    let ref_sink = MemorySink::new();
    generate_pyramid(&raster, &plan, &ref_sink, &EngineConfig::default()).unwrap();

    let conc_sink = MemorySink::new();
    let config = EngineConfig::default().with_concurrency(4);
    generate_pyramid(&raster, &plan, &conc_sink, &config).unwrap();

    let mut ref_tiles = ref_sink.tiles();
    let mut conc_tiles = conc_sink.tiles();
    ref_tiles.sort_by_key(|t| (t.coord.level, t.coord.row, t.coord.col));
    conc_tiles.sort_by_key(|t| (t.coord.level, t.coord.row, t.coord.col));

    assert_eq!(ref_tiles.len(), conc_tiles.len());
    for (r, c) in ref_tiles.iter().zip(conc_tiles.iter()) {
        assert_eq!(r.coord, c.coord);
        assert_eq!(r.data, c.data, "Concurrent output differs at {:?}", r.coord);
    }
}

/// Two sequential runs produce identical output (determinism).
#[test]
fn google_centre_portrait_deterministic() {
    let raster = load_portrait_raster();
    let planner = PyramidPlanner::new(raster.width(), raster.height(), 256, 0, Layout::Google)
        .unwrap()
        .with_centre(true);
    let plan = planner.plan();

    let sink1 = MemorySink::new();
    let sink2 = MemorySink::new();
    let config = EngineConfig::default();

    generate_pyramid(&raster, &plan, &sink1, &config).unwrap();
    generate_pyramid(&raster, &plan, &sink2, &config).unwrap();

    let mut tiles1 = sink1.tiles();
    let mut tiles2 = sink2.tiles();
    tiles1.sort_by_key(|t| (t.coord.level, t.coord.row, t.coord.col));
    tiles2.sort_by_key(|t| (t.coord.level, t.coord.row, t.coord.col));

    assert_eq!(tiles1.len(), tiles2.len());
    for (t1, t2) in tiles1.iter().zip(tiles2.iter()) {
        assert_eq!(t1.coord, t2.coord);
        assert_eq!(t1.data, t2.data, "Tile {:?} differs between runs", t1.coord);
    }
}

// ---------------------------------------------------------------------------
// Google layout structural tests (blueprint PDF)
// ---------------------------------------------------------------------------

/// Verify plan structure for blueprint.pdf (landscape/wide format).
#[test]
fn google_centre_blueprint_plan_structure() {
    let raster = load_blueprint_raster();
    let w = raster.width();
    let h = raster.height();

    let planner = PyramidPlanner::new(w, h, 256, 0, Layout::Google)
        .unwrap()
        .with_centre(true);
    let plan = planner.plan();

    // Verify power-of-2 grids
    for (i, level) in plan.levels.iter().enumerate() {
        let expected_grid = 1u32 << i;
        assert_eq!(level.cols, expected_grid, "Level {} cols", i);
        assert_eq!(level.rows, expected_grid, "Level {} rows", i);
    }

    // Canvas should be square
    assert_eq!(plan.canvas_width, plan.canvas_height);

    // Centre offsets should centre the image
    let canvas = plan.canvas_width;
    assert_eq!(plan.centre_offset_x, (canvas - w) / 2);
    assert_eq!(plan.centre_offset_y, (canvas - h) / 2);
}

/// Generate and verify all tiles for blueprint.pdf.
#[test]
fn google_centre_blueprint_generates_all_tiles() {
    let raster = load_blueprint_raster();
    let planner = PyramidPlanner::new(raster.width(), raster.height(), 256, 0, Layout::Google)
        .unwrap()
        .with_centre(true);
    let plan = planner.plan();
    let sink = MemorySink::new();

    let result = generate_pyramid(&raster, &plan, &sink, &EngineConfig::default()).unwrap();
    assert_eq!(result.tiles_produced, plan.total_tile_count());
}

// ---------------------------------------------------------------------------
// Google layout WITHOUT centre
// ---------------------------------------------------------------------------

/// Google layout without centre: offsets should be zero, image pinned to (0,0).
#[test]
fn google_no_centre_portrait_plan() {
    let planner = PyramidPlanner::new(3300, 5024, 256, 0, Layout::Google).unwrap();
    let plan = planner.plan();

    assert_eq!(plan.centre_offset_x, 0);
    assert_eq!(plan.centre_offset_y, 0);
    assert!(!plan.centre);
    assert_eq!(plan.level_count(), 6);
    assert_eq!(plan.canvas_width, 8192);
}

/// Google layout without centre generates valid tiles.
#[test]
fn google_no_centre_portrait_generates_tiles() {
    let raster = load_portrait_raster();
    let planner =
        PyramidPlanner::new(raster.width(), raster.height(), 256, 0, Layout::Google).unwrap();
    let plan = planner.plan();
    let sink = MemorySink::new();

    let result = generate_pyramid(&raster, &plan, &sink, &EngineConfig::default()).unwrap();
    assert_eq!(result.tiles_produced, plan.total_tile_count());
}

// ---------------------------------------------------------------------------
// Decoded pixel comparison against vips fixtures
// ---------------------------------------------------------------------------

/// Compare libviprs Google+centre portrait output against vips fixtures.
/// For tiles vips produced, compare decoded pixels. For tiles vips omitted
/// (blank tiles), verify libviprs output is solid background.
#[test]
fn google_centre_portrait_matches_vips_fixtures() {
    let raster = load_portrait_raster();
    let planner = PyramidPlanner::new(raster.width(), raster.height(), 256, 0, Layout::Google)
        .unwrap()
        .with_centre(true);
    let plan = planner.plan();

    let dir = tempfile::tempdir().unwrap();
    let base = dir.path().join("portrait_google");
    let sink = FsSink::new(base.clone(), plan.clone(), TileFormat::Png);
    generate_pyramid(&raster, &plan, &sink, &EngineConfig::default()).unwrap();

    // Collect vips fixture tiles (excludes blank.png and vips-properties.xml)
    let vips_files = collect_files(Path::new(EXPECTED_PORTRAIT_GOOGLE), "png");
    let vips_tiles: Vec<_> = vips_files
        .iter()
        .filter(|(p, _)| p != "blank.png")
        .collect();
    let vips_paths: HashSet<&str> = vips_tiles.iter().map(|(p, _)| p.as_str()).collect();

    // Collect libviprs tiles
    let actual_files = collect_files(&base, "png");

    // For every tile vips produced, compare decoded pixels.
    // Tolerance accounts for downscaling algorithm differences between
    // vips (libvips area averaging) and libviprs.
    // DeepZoom tiles match vips at tolerance=0 since downscale_half
    // exactly replicates vips's region-shrink=mean. Google+centre tiles
    // have higher divergence because centre offset scaling (bit-shift)
    // can place the image-background boundary at different sub-pixel
    // positions than vips. Boundary pixels at deep levels show large
    // diffs (up to ~100) while interior/exterior pixels match exactly.
    // TODO: investigate vips's centre offset computation to close gap.
    let tolerance: u8 = 0;
    let mut matched = 0;
    let mut max_diff: u8 = 0;
    for (act_path, act_bytes) in &actual_files {
        if let Some((_, vips_bytes)) = vips_tiles.iter().find(|(p, _)| p == act_path) {
            let (vw, vh, vpx) = decode_png(vips_bytes);
            let (aw, ah, apx) = decode_png(act_bytes);
            assert_eq!(
                (vw, vh),
                (aw, ah),
                "Dimension mismatch at {act_path}: vips {vw}x{vh}, libviprs {aw}x{ah}"
            );
            for (i, (&vp, &ap)) in vpx.iter().zip(apx.iter()).enumerate() {
                let diff = (vp as i16 - ap as i16).unsigned_abs() as u8;
                if diff > max_diff {
                    max_diff = diff;
                }
                assert!(
                    diff <= tolerance,
                    "Pixel mismatch at {act_path} byte {i}: vips={vp} libviprs={ap} diff={diff}"
                );
            }
            matched += 1;
        }
    }
    eprintln!("portrait google centre: max_diff={max_diff}, tolerance={tolerance}");

    assert_eq!(
        matched,
        vips_tiles.len(),
        "Expected to match {} vips tiles, matched {}",
        vips_tiles.len(),
        matched
    );

    // For tiles libviprs produced but vips omitted, verify they are nearly blank.
    // vips skips tiles that are close to the background color (skip-blanks threshold).
    // Due to downscaling algorithm differences, libviprs may produce slightly
    // non-white pixels near the image boundary at lower levels.
    let mut blank_count = 0;
    for (act_path, act_bytes) in &actual_files {
        if !vips_paths.contains(act_path.as_str()) {
            let (_, _, pixels) = decode_png(act_bytes);
            let max_deviation = pixels.iter().map(|&b| 255u8.abs_diff(b)).max().unwrap_or(0);
            assert!(
                max_deviation <= tolerance,
                "Tile {act_path} was omitted by vips but has pixels {max_deviation} from background (tolerance {tolerance})"
            );
            blank_count += 1;
        }
    }

    eprintln!(
        "portrait google: {} tiles matched vips, {} blank tiles verified",
        matched, blank_count
    );
}

/// Compare libviprs Google+centre mix output against vips fixtures.
#[test]
fn google_centre_mix_matches_vips_fixtures() {
    let raster = load_mix_raster();
    let planner = PyramidPlanner::new(raster.width(), raster.height(), 256, 0, Layout::Google)
        .unwrap()
        .with_centre(true);
    let plan = planner.plan();

    let dir = tempfile::tempdir().unwrap();
    let base = dir.path().join("mix_google");
    let sink = FsSink::new(base.clone(), plan.clone(), TileFormat::Png);
    generate_pyramid(&raster, &plan, &sink, &EngineConfig::default()).unwrap();

    let vips_files = collect_files(Path::new(EXPECTED_MIX_GOOGLE), "png");
    let vips_tiles: Vec<_> = vips_files
        .iter()
        .filter(|(p, _)| p != "blank.png")
        .collect();
    let vips_paths: HashSet<&str> = vips_tiles.iter().map(|(p, _)| p.as_str()).collect();

    let actual_files = collect_files(&base, "png");

    let tolerance: u8 = 0;
    let mut matched = 0;
    let mut max_diff: u8 = 0;
    for (act_path, act_bytes) in &actual_files {
        if let Some((_, vips_bytes)) = vips_tiles.iter().find(|(p, _)| p == act_path) {
            let (vw, vh, vpx) = decode_png(vips_bytes);
            let (aw, ah, apx) = decode_png(act_bytes);
            assert_eq!(
                (vw, vh),
                (aw, ah),
                "Dimension mismatch at {act_path}: vips {vw}x{vh}, libviprs {aw}x{ah}"
            );
            for (i, (&vp, &ap)) in vpx.iter().zip(apx.iter()).enumerate() {
                let diff = (vp as i16 - ap as i16).unsigned_abs() as u8;
                if diff > max_diff {
                    max_diff = diff;
                }
                assert!(
                    diff <= tolerance,
                    "Pixel mismatch at {act_path} byte {i}: vips={vp} libviprs={ap} diff={diff}"
                );
            }
            matched += 1;
        }
    }
    eprintln!("mix google centre: max_diff={max_diff}, tolerance={tolerance}");

    assert_eq!(matched, vips_tiles.len());

    let mut blank_count = 0;
    for (act_path, act_bytes) in &actual_files {
        if !vips_paths.contains(act_path.as_str()) {
            let (_, _, pixels) = decode_png(act_bytes);
            let max_deviation = pixels.iter().map(|&b| 255u8.abs_diff(b)).max().unwrap_or(0);
            assert!(
                max_deviation <= tolerance,
                "Tile {act_path} omitted by vips but has pixels {max_deviation} from background"
            );
            blank_count += 1;
        }
    }

    eprintln!(
        "mix google: {} tiles matched vips, {} blank tiles verified",
        matched, blank_count
    );
}
