//! Rotation parity against an independent libvips reference.
//!
//! libviprs renders PDF pages through pdfium's matrix path. pdfium already
//! applies the page's intrinsic `/Rotate` in its own display matrix, so the
//! strip matrix libviprs supplies must be rotation-free (a pure scale +
//! strip translation). A previous implementation hand-derived a per-`/Rotate`
//! matrix that double-applied the rotation, transposing and clipping rotated
//! pages — a bug the self-referential `pdfium_streaming_rotation_matrix.rs`
//! could not catch, because it compares strips against a full render produced
//! by the *same* matrix path (both wrong identically).
//!
//! This test closes that gap with an **independent** oracle: golden images
//! rendered by **libvips built with the same pdfium engine** (chromium/7881
//! from libviprs-dep, the exact build libviprs ships). The goldens live in
//! `tests/fixtures/rotation_libvips_pdfium_expected/` and are regenerated by
//! `tools/gen_pdfium_goldens.py` (a Dockerised libvips+pdfium build). Both the
//! input PDFs and the expected PNGs are committed fixtures; nothing is
//! generated at test time.
//!
//! The comparison is **per-pixel** (mean absolute difference over every
//! channel of every pixel), not a channel-mean summary — a rotation error
//! rearranges colours without changing their histogram, so a channel-mean
//! check would pass on a transposed page. Since both sides rasterise with
//! pdfium 7881, a correct render sits far below 1.0; the historical bug drove
//! this to 78–99.

#![cfg(feature = "pdfium")]

use libviprs::PdfiumStripSource;
use libviprs::streaming::StripSource;

/// (input PDF, expected libvips+pdfium golden) fixture pairs. The `/Rotate 0`
/// case (`canonical.pdf`) anchors that the flag-free path is unchanged; the
/// three rotated cases are where the double-apply bug manifested.
const CASES: &[(&str, &str)] = &[
    ("canonical.pdf", "canonical.png"),
    ("canonical_rotated_90.pdf", "canonical_rotated_90.png"),
    ("canonical_rotated_180.pdf", "canonical_rotated_180.png"),
    ("canonical_rotated_270.pdf", "canonical_rotated_270.png"),
];

/// Goldens are rendered at 72 dpi (1 pt == 1 px); libviprs must match.
const DPI: u32 = 72;

/// Per-pixel mean absolute difference across all RGBA channels. libvips and
/// libviprs both rasterise with pdfium 7881, so a correct render is within a
/// fraction of a level; the rotation bug produced ~78–99. 2.0 leaves a ~40x
/// margin while still failing hard on any transposed/clipped output.
const MEAN_ABS_DIFF_TOLERANCE: f64 = 2.0;

fn fixture(name: &str) -> String {
    format!("{}/tests/fixtures/{name}", env!("CARGO_MANIFEST_DIR"))
}

fn mean_abs_diff(a: &[u8], b: &[u8]) -> f64 {
    assert_eq!(a.len(), b.len());
    let sum: u64 = a
        .iter()
        .zip(b)
        .map(|(x, y)| (*x as i64 - *y as i64).unsigned_abs())
        .sum();
    sum as f64 / a.len() as f64
}

#[test]
fn rotation_matches_libvips_pdfium_golden() {
    for (pdf, golden) in CASES {
        let source = PdfiumStripSource::new_streaming(fixture(pdf), 1, DPI)
            .unwrap_or_else(|e| panic!("{pdf}: new_streaming failed: {e:?}"));

        // Render the whole page as a single strip through the matrix path.
        let height = source.height();
        let raster = source
            .render_strip(0, height)
            .unwrap_or_else(|e| panic!("{pdf}: render_strip failed: {e:?}"));
        let (w, h) = (raster.width(), raster.height());

        let expected = image::open(fixture(&format!(
            "rotation_libvips_pdfium_expected/{golden}"
        )))
        .unwrap_or_else(|e| panic!("{golden}: open failed: {e:?}"))
        .to_rgba8();

        assert_eq!(
            (w, h),
            (expected.width(), expected.height()),
            "{pdf}: dimensions differ from libvips golden",
        );

        let diff = mean_abs_diff(raster.data(), expected.as_raw());
        println!("{pdf}: {w}x{h} mean|diff| vs libvips+pdfium golden = {diff:.4}");
        assert!(
            diff <= MEAN_ABS_DIFF_TOLERANCE,
            "{pdf}: per-pixel mean abs diff {diff:.4} > {MEAN_ABS_DIFF_TOLERANCE} \
             vs libvips+pdfium golden — rotation is being mis-applied",
        );
    }
}
